// swift-tools-version: 6.2
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import PackageDescription

let package = Package(
  name: "GoogleCloudDialogflowCXV3",
  platforms: [.macOS(.v15)],
  products: [
    .library(name: "GoogleCloudDialogflowCXV3", targets: ["GoogleCloudDialogflowCXV3"])
  ],
  traits: [
    .trait(
      name: "Agents",
    ),
    .trait(
      name: "Changelogs",
    ),
    .trait(
      name: "Deployments",
    ),
    .trait(
      name: "EntityTypes",
    ),
    .trait(
      name: "Environments",
    ),
    .trait(
      name: "Examples",
    ),
    .trait(
      name: "Experiments",
    ),
    .trait(
      name: "Flows",
    ),
    .trait(
      name: "Generators",
    ),
    .trait(
      name: "Intents",
    ),
    .trait(
      name: "Pages",
    ),
    .trait(
      name: "Playbooks",
    ),
    .trait(
      name: "SecuritySettingsService",
    ),
    .trait(
      name: "SessionEntityTypes",
    ),
    .trait(
      name: "Sessions",
    ),
    .trait(
      name: "TestCases",
    ),
    .trait(
      name: "Tools",
    ),
    .trait(
      name: "TransitionRouteGroups",
    ),
    .trait(
      name: "Versions",
    ),
    .trait(
      name: "Webhooks",
    ),
    .default(enabledTraits: [
      "Agents"
    ]),
  ],
  dependencies: [
    .package(path: "../../packages/auth"),
    .package(path: "../../packages/gax"),
    .package(path: "../../generated/google-cloud-location"),
    .package(path: "../../packages/wkt"),
    .package(path: "../../generated/google-longrunning"),
    .package(path: "../../generated/google-rpc"),
    .package(path: "../../generated/google-type"),
    .package(url: "https://github.com/apple/swift-log", from: "1.12.0"),
  ],
  targets: [
    .target(
      name: "GoogleCloudDialogflowCXV3",
      dependencies: [
        .product(name: "GoogleCloudAuth", package: "auth"),
        .product(name: "GoogleCloudGax", package: "gax"),
        .product(name: "GoogleCloudLocation", package: "google-cloud-location"),
        .product(name: "GoogleCloudWkt", package: "wkt"),
        .product(name: "GoogleLongRunning", package: "google-longrunning"),
        .product(name: "GoogleRpc", package: "google-rpc"),
        .product(name: "GoogleType", package: "google-type"),
        .product(name: "Logging", package: "swift-log"),
      ],
    )
  ]
)
