// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Changelogs
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Changelogs represents a change made to a given agent.
  public struct Changelog: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The unique identifier of the changelog.
    /// Format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/changelogs/<ChangelogID>`.
    public var name: Swift.String = Swift.String()

    /// Email address of the authenticated user.
    public var userEmail: Swift.String = Swift.String()

    /// The affected resource display name of the change.
    public var displayName: Swift.String = Swift.String()

    /// The action of the change.
    public var action: Swift.String = Swift.String()

    /// The affected resource type.
    public var type: Swift.String = Swift.String()

    /// The affected resource name of the change.
    public var resource: Swift.String = Swift.String()

    /// The timestamp of the change.
    public var createTime: GoogleCloudWKT.Timestamp? = nil

    /// The affected language code of the change.
    public var languageCode: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `Changelog`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Changelog().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let userEmail = CodingKeys(stringValue: "userEmail")
      static let displayName = CodingKeys(stringValue: "displayName")
      static let action = CodingKeys(stringValue: "action")
      static let type = CodingKeys(stringValue: "type")
      static let resource = CodingKeys(stringValue: "resource")
      static let createTime = CodingKeys(stringValue: "createTime")
      static let languageCode = CodingKeys(stringValue: "languageCode")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "userEmail",
        "displayName",
        "action",
        "type",
        "resource",
        "createTime",
        "languageCode",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .userEmail) {
        self.userEmail = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
        self.displayName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .action) {
        self.action = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .type) {
        self.type = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resource) {
        self.resource = value
      }
      self.createTime = try container.decodeIfPresent(
        GoogleCloudWKT.Timestamp.self, forKey: .createTime)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
        self.languageCode = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.userEmail, forKey: .userEmail)
      try container.encode(self.displayName, forKey: .displayName)
      try container.encode(self.action, forKey: .action)
      try container.encode(self.type, forKey: .type)
      try container.encode(self.resource, forKey: .resource)
      try container.encodeIfPresent(self.createTime, forKey: .createTime)
      try container.encode(self.languageCode, forKey: .languageCode)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.Changelog"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
