// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Environments
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleCloudWkt
  import GoogleLongrunning
  import GoogleRpc
  import GoogleCloudGax

  /// Service for managing
  /// [Environments][google.cloud.dialogflow.cx.v3.Environment].
  ///
  /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
  ///
  /// @Snippet(path: "EnvironmentsQuickstart")
  public class EnvironmentsClient: Clients.EnvironmentsProtocol {
    let inner: any Clients.EnvironmentsStub

    /// Creates a new `EnvironmentsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any Clients.EnvironmentsStub = try Clients.EnvironmentsTransport(options)
      inner = Clients.EnvironmentsRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.EnvironmentsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Returns the list of all environments in the specified
    /// [Agent][google.cloud.dialogflow.cx.v3.Agent].
    ///
    /// [google.cloud.dialogflow.cx.v3.Agent]: <doc:Agent>
    ///
    /// @Snippet(path: "Environments_ListEnvironments")
    public func listEnvironments(
      request: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCxV3.ListEnvironmentsResponse {
      try await self.inner.listEnvironments(request: request, options: options)
    }

    /// Returns the list of all environments in the specified
    /// [Agent][google.cloud.dialogflow.cx.v3.Agent].
    ///
    /// [google.cloud.dialogflow.cx.v3.Agent]: <doc:Agent>
    ///
    /// @Snippet(path: "Environments_ListEnvironments")
    public func listEnvironments(
      byItem: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Environment, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDialogflowCxV3.ListEnvironmentsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listEnvironments(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Retrieves the specified
    /// [Environment][google.cloud.dialogflow.cx.v3.Environment].
    ///
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    ///
    /// @Snippet(path: "Environments_GetEnvironment")
    public func getEnvironment(
      request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCxV3.Environment {
      try await self.inner.getEnvironment(request: request, options: options)
    }

    /// Creates an [Environment][google.cloud.dialogflow.cx.v3.Environment] in the
    /// specified [Agent][google.cloud.dialogflow.cx.v3.Agent].
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`: An empty [Struct
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct)
    /// - `response`: [Environment][google.cloud.dialogflow.cx.v3.Environment]
    ///
    /// [google.cloud.dialogflow.cx.v3.Agent]: <doc:Agent>
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    ///
    /// @Snippet(path: "Environments_CreateEnvironment")
    public func createEnvironment(
      request: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.createEnvironment(request: request, options: options)
    }

    /// Creates an [Environment][google.cloud.dialogflow.cx.v3.Environment] in the
    /// specified [Agent][google.cloud.dialogflow.cx.v3.Agent].
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`: An empty [Struct
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct)
    /// - `response`: [Environment][google.cloud.dialogflow.cx.v3.Environment]
    ///
    /// [google.cloud.dialogflow.cx.v3.Agent]: <doc:Agent>
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    ///
    /// @Snippet(path: "Environments_CreateEnvironment")
    public func createEnvironment(
      withPolling: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Environment(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.createEnvironment(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// Updates the specified
    /// [Environment][google.cloud.dialogflow.cx.v3.Environment].
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`: An empty [Struct
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct)
    /// - `response`: [Environment][google.cloud.dialogflow.cx.v3.Environment]
    ///
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    ///
    /// @Snippet(path: "Environments_UpdateEnvironment")
    public func updateEnvironment(
      request: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.updateEnvironment(request: request, options: options)
    }

    /// Updates the specified
    /// [Environment][google.cloud.dialogflow.cx.v3.Environment].
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`: An empty [Struct
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct)
    /// - `response`: [Environment][google.cloud.dialogflow.cx.v3.Environment]
    ///
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    ///
    /// @Snippet(path: "Environments_UpdateEnvironment")
    public func updateEnvironment(
      withPolling: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Environment(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.updateEnvironment(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// Deletes the specified
    /// [Environment][google.cloud.dialogflow.cx.v3.Environment].
    ///
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    ///
    /// @Snippet(path: "Environments_DeleteEnvironment")
    public func deleteEnvironment(
      request: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteEnvironment(request: request, options: options)
    }

    /// Looks up the history of the specified
    /// [Environment][google.cloud.dialogflow.cx.v3.Environment].
    ///
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    ///
    /// @Snippet(path: "Environments_LookupEnvironmentHistory")
    public func lookupEnvironmentHistory(
      request: LookupEnvironmentHistoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCxV3.LookupEnvironmentHistoryResponse {
      try await self.inner.lookupEnvironmentHistory(request: request, options: options)
    }

    /// Looks up the history of the specified
    /// [Environment][google.cloud.dialogflow.cx.v3.Environment].
    ///
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    ///
    /// @Snippet(path: "Environments_LookupEnvironmentHistory")
    public func lookupEnvironmentHistory(
      byItem: LookupEnvironmentHistoryRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Environment, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws
          -> GoogleCloudDialogflowCxV3.LookupEnvironmentHistoryResponse in
        var request = byItem
        request.pageToken = token
        return try await self.lookupEnvironmentHistory(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Kicks off a continuous test under the specified
    /// [Environment][google.cloud.dialogflow.cx.v3.Environment].
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`:
    /// [RunContinuousTestMetadata][google.cloud.dialogflow.cx.v3.RunContinuousTestMetadata]
    /// - `response`:
    /// [RunContinuousTestResponse][google.cloud.dialogflow.cx.v3.RunContinuousTestResponse]
    ///
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    /// [google.cloud.dialogflow.cx.v3.RunContinuousTestMetadata]: <doc:RunContinuousTestMetadata>
    /// [google.cloud.dialogflow.cx.v3.RunContinuousTestResponse]: <doc:RunContinuousTestResponse>
    ///
    /// @Snippet(path: "Environments_RunContinuousTest")
    public func runContinuousTest(
      request: RunContinuousTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.runContinuousTest(request: request, options: options)
    }

    /// Kicks off a continuous test under the specified
    /// [Environment][google.cloud.dialogflow.cx.v3.Environment].
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`:
    /// [RunContinuousTestMetadata][google.cloud.dialogflow.cx.v3.RunContinuousTestMetadata]
    /// - `response`:
    /// [RunContinuousTestResponse][google.cloud.dialogflow.cx.v3.RunContinuousTestResponse]
    ///
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    /// [google.cloud.dialogflow.cx.v3.RunContinuousTestMetadata]: <doc:RunContinuousTestMetadata>
    /// [google.cloud.dialogflow.cx.v3.RunContinuousTestResponse]: <doc:RunContinuousTestResponse>
    ///
    /// @Snippet(path: "Environments_RunContinuousTest")
    public func runContinuousTest(
      withPolling: RunContinuousTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<RunContinuousTestResponse> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<RunContinuousTestResponse>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try RunContinuousTestResponse(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.runContinuousTest(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<RunContinuousTestResponse>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// Fetches a list of continuous test results for a given environment.
    ///
    /// @Snippet(path: "Environments_ListContinuousTestResults")
    public func listContinuousTestResults(
      request: ListContinuousTestResultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCxV3.ListContinuousTestResultsResponse {
      try await self.inner.listContinuousTestResults(request: request, options: options)
    }

    /// Fetches a list of continuous test results for a given environment.
    ///
    /// @Snippet(path: "Environments_ListContinuousTestResults")
    public func listContinuousTestResults(
      byItem: ListContinuousTestResultsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ContinuousTestResult, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws
          -> GoogleCloudDialogflowCxV3.ListContinuousTestResultsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listContinuousTestResults(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Deploys a flow to the specified
    /// [Environment][google.cloud.dialogflow.cx.v3.Environment].
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`:
    /// [DeployFlowMetadata][google.cloud.dialogflow.cx.v3.DeployFlowMetadata]
    /// - `response`:
    /// [DeployFlowResponse][google.cloud.dialogflow.cx.v3.DeployFlowResponse]
    ///
    /// [google.cloud.dialogflow.cx.v3.DeployFlowMetadata]: <doc:DeployFlowMetadata>
    /// [google.cloud.dialogflow.cx.v3.DeployFlowResponse]: <doc:DeployFlowResponse>
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    ///
    /// @Snippet(path: "Environments_DeployFlow")
    public func deployFlow(
      request: DeployFlowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deployFlow(request: request, options: options)
    }

    /// Deploys a flow to the specified
    /// [Environment][google.cloud.dialogflow.cx.v3.Environment].
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`:
    /// [DeployFlowMetadata][google.cloud.dialogflow.cx.v3.DeployFlowMetadata]
    /// - `response`:
    /// [DeployFlowResponse][google.cloud.dialogflow.cx.v3.DeployFlowResponse]
    ///
    /// [google.cloud.dialogflow.cx.v3.DeployFlowMetadata]: <doc:DeployFlowMetadata>
    /// [google.cloud.dialogflow.cx.v3.DeployFlowResponse]: <doc:DeployFlowResponse>
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    ///
    /// @Snippet(path: "Environments_DeployFlow")
    public func deployFlow(
      withPolling: DeployFlowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<DeployFlowResponse> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<DeployFlowResponse>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try DeployFlowResponse(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.deployFlow(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<DeployFlowResponse>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name] field:
    ///
    /// * **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// @Snippet(path: "Environments_ListLocations")
    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name] field:
    ///
    /// * **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// @Snippet(path: "Environments_ListLocations")
    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Gets information about a location.
    ///
    /// @Snippet(path: "Environments_GetLocation")
    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    ///
    /// @Snippet(path: "Environments_ListOperations")
    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    ///
    /// @Snippet(path: "Environments_ListOperations")
    public func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    ///
    /// @Snippet(path: "Environments_GetOperation")
    func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    ///
    /// @Snippet(path: "Environments_CancelOperation")
    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `EnvironmentsClient`.
    ///
    /// To mock `EnvironmentsClient` change your functions to receive
    /// `some EnvironmentsProtocol` or `any EnvironmentsProtocol`
    /// and pass a mock implementation in your tests.
    public protocol EnvironmentsProtocol {
      /// See `EnvironmentsClient.listEnvironments`.
      func listEnvironments(request: ListEnvironmentsRequest) async throws
        -> GoogleCloudDialogflowCxV3.ListEnvironmentsResponse

      /// See `EnvironmentsClient.listEnvironments`.
      func listEnvironments(
        byItem: ListEnvironmentsRequest
      ) throws -> any AsyncSequence<Environment, Swift.Error>

      /// See `EnvironmentsClient.listEnvironments`.
      func listEnvironments(
        parent: Swift.String,
      ) throws -> any AsyncSequence<Environment, Swift.Error>

      /// See `EnvironmentsClient.getEnvironment`.
      func getEnvironment(request: GetEnvironmentRequest) async throws
        -> GoogleCloudDialogflowCxV3.Environment

      /// See `EnvironmentsClient.getEnvironment`.
      func getEnvironment(
        name: Swift.String,
      ) async throws -> GoogleCloudDialogflowCxV3.Environment

      /// See `EnvironmentsClient.createEnvironment`.
      func createEnvironment(request: CreateEnvironmentRequest) async throws
        -> GoogleLongrunning.Operation

      /// See `EnvironmentsClient.createEnvironment`.
      func createEnvironment(withPolling: CreateEnvironmentRequest) async throws
        -> any GoogleCloudGax.PollableOperation<Environment>

      /// See `EnvironmentsClient.createEnvironment`.
      func createEnvironment(
        parent: Swift.String,
        environment: Environment?,
      ) async throws -> any GoogleCloudGax.PollableOperation<Environment>

      /// See `EnvironmentsClient.updateEnvironment`.
      func updateEnvironment(request: UpdateEnvironmentRequest) async throws
        -> GoogleLongrunning.Operation

      /// See `EnvironmentsClient.updateEnvironment`.
      func updateEnvironment(withPolling: UpdateEnvironmentRequest) async throws
        -> any GoogleCloudGax.PollableOperation<Environment>

      /// See `EnvironmentsClient.updateEnvironment`.
      func updateEnvironment(
        environment: Environment?,
        updateMask: GoogleCloudWkt.FieldMask?,
      ) async throws -> any GoogleCloudGax.PollableOperation<Environment>

      /// See `EnvironmentsClient.deleteEnvironment`.
      func deleteEnvironment(request: DeleteEnvironmentRequest) async throws

      /// See `EnvironmentsClient.deleteEnvironment`.
      func deleteEnvironment(
        name: Swift.String,
      ) async throws

      /// See `EnvironmentsClient.lookupEnvironmentHistory`.
      func lookupEnvironmentHistory(request: LookupEnvironmentHistoryRequest) async throws
        -> GoogleCloudDialogflowCxV3.LookupEnvironmentHistoryResponse

      /// See `EnvironmentsClient.lookupEnvironmentHistory`.
      func lookupEnvironmentHistory(
        byItem: LookupEnvironmentHistoryRequest
      ) throws -> any AsyncSequence<Environment, Swift.Error>

      /// See `EnvironmentsClient.lookupEnvironmentHistory`.
      func lookupEnvironmentHistory(
        name: Swift.String,
      ) throws -> any AsyncSequence<Environment, Swift.Error>

      /// See `EnvironmentsClient.runContinuousTest`.
      func runContinuousTest(request: RunContinuousTestRequest) async throws
        -> GoogleLongrunning.Operation

      /// See `EnvironmentsClient.runContinuousTest`.
      func runContinuousTest(withPolling: RunContinuousTestRequest) async throws
        -> any GoogleCloudGax.PollableOperation<RunContinuousTestResponse>

      /// See `EnvironmentsClient.listContinuousTestResults`.
      func listContinuousTestResults(request: ListContinuousTestResultsRequest) async throws
        -> GoogleCloudDialogflowCxV3.ListContinuousTestResultsResponse

      /// See `EnvironmentsClient.listContinuousTestResults`.
      func listContinuousTestResults(
        byItem: ListContinuousTestResultsRequest
      ) throws -> any AsyncSequence<ContinuousTestResult, Swift.Error>

      /// See `EnvironmentsClient.listContinuousTestResults`.
      func listContinuousTestResults(
        parent: Swift.String,
      ) throws -> any AsyncSequence<ContinuousTestResult, Swift.Error>

      /// See `EnvironmentsClient.deployFlow`.
      func deployFlow(request: DeployFlowRequest) async throws -> GoogleLongrunning.Operation

      /// See `EnvironmentsClient.deployFlow`.
      func deployFlow(withPolling: DeployFlowRequest) async throws -> any GoogleCloudGax
        .PollableOperation<DeployFlowResponse>

      /// See `EnvironmentsClient.listLocations`.
      func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
        -> GoogleCloudLocation.ListLocationsResponse

      /// See `EnvironmentsClient.listLocations`.
      func listLocations(
        byItem: GoogleCloudLocation.ListLocationsRequest
      ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

      /// See `EnvironmentsClient.getLocation`.
      func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
        -> GoogleCloudLocation.Location

      /// See `EnvironmentsClient.listOperations`.
      func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
        -> GoogleLongrunning.ListOperationsResponse

      /// See `EnvironmentsClient.listOperations`.
      func listOperations(
        byItem: GoogleLongrunning.ListOperationsRequest
      ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

      /// See `EnvironmentsClient.listOperations`.
      func listOperations(
        name: Swift.String,
        filter: Swift.String,
      ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

      /// See `EnvironmentsClient.cancelOperation`.
      func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws

      /// See `EnvironmentsClient.cancelOperation`.
      func cancelOperation(
        name: Swift.String,
      ) async throws

      /// See `EnvironmentsClient.listEnvironments`.
      func listEnvironments(
        request: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCxV3.ListEnvironmentsResponse

      /// See `EnvironmentsClient.listEnvironments`.
      func listEnvironments(
        byItem: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<Environment, Swift.Error>

      /// See `EnvironmentsClient.getEnvironment`.
      func getEnvironment(
        request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCxV3.Environment

      /// See `EnvironmentsClient.createEnvironment`.
      func createEnvironment(
        request: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation

      /// See `EnvironmentsClient.createEnvironment`.
      func createEnvironment(
        withPolling: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> any GoogleCloudGax.PollableOperation<Environment>

      /// See `EnvironmentsClient.updateEnvironment`.
      func updateEnvironment(
        request: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation

      /// See `EnvironmentsClient.updateEnvironment`.
      func updateEnvironment(
        withPolling: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> any GoogleCloudGax.PollableOperation<Environment>

      /// See `EnvironmentsClient.deleteEnvironment`.
      func deleteEnvironment(
        request: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      /// See `EnvironmentsClient.lookupEnvironmentHistory`.
      func lookupEnvironmentHistory(
        request: LookupEnvironmentHistoryRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCxV3.LookupEnvironmentHistoryResponse

      /// See `EnvironmentsClient.lookupEnvironmentHistory`.
      func lookupEnvironmentHistory(
        byItem: LookupEnvironmentHistoryRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<Environment, Swift.Error>

      /// See `EnvironmentsClient.runContinuousTest`.
      func runContinuousTest(
        request: RunContinuousTestRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation

      /// See `EnvironmentsClient.runContinuousTest`.
      func runContinuousTest(
        withPolling: RunContinuousTestRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> any GoogleCloudGax.PollableOperation<RunContinuousTestResponse>

      /// See `EnvironmentsClient.listContinuousTestResults`.
      func listContinuousTestResults(
        request: ListContinuousTestResultsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCxV3.ListContinuousTestResultsResponse

      /// See `EnvironmentsClient.listContinuousTestResults`.
      func listContinuousTestResults(
        byItem: ListContinuousTestResultsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<ContinuousTestResult, Swift.Error>

      /// See `EnvironmentsClient.deployFlow`.
      func deployFlow(
        request: DeployFlowRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.Operation

      /// See `EnvironmentsClient.deployFlow`.
      func deployFlow(
        withPolling: DeployFlowRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> any GoogleCloudGax.PollableOperation<DeployFlowResponse>

      /// See `EnvironmentsClient.listLocations`.
      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      /// See `EnvironmentsClient.listLocations`.
      func listLocations(
        byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

      /// See `EnvironmentsClient.getLocation`.
      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      /// See `EnvironmentsClient.listOperations`.
      func listOperations(
        request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.ListOperationsResponse

      /// See `EnvironmentsClient.listOperations`.
      func listOperations(
        byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

      /// See `EnvironmentsClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws
    }
  }

  // Default implementations
  extension Clients.EnvironmentsProtocol {
    public func listEnvironments(request: ListEnvironmentsRequest) async throws
      -> GoogleCloudDialogflowCxV3.ListEnvironmentsResponse
    {
      try await self.listEnvironments(request: request, options: .init())
    }

    public func listEnvironments(
      request: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCxV3.ListEnvironmentsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listEnvironments(
      byItem: ListEnvironmentsRequest
    ) throws -> any AsyncSequence<Environment, Swift.Error> {
      try self.listEnvironments(byItem: byItem, options: .init())
    }

    public func listEnvironments(
      byItem: ListEnvironmentsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Environment, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDialogflowCxV3.ListEnvironmentsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listEnvironments(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Environment, Swift.Error> {
      let request = ListEnvironmentsRequest().with {
        $0.parent = parent
      }
      return try self.listEnvironments(byItem: request)
    }

    public func getEnvironment(request: GetEnvironmentRequest) async throws
      -> GoogleCloudDialogflowCxV3.Environment
    {
      try await self.getEnvironment(request: request, options: .init())
    }

    public func getEnvironment(
      request: GetEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCxV3.Environment {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getEnvironment(
      name: Swift.String,
    ) async throws -> GoogleCloudDialogflowCxV3.Environment {
      let request = GetEnvironmentRequest().with {
        $0.name = name
      }
      return try await self.getEnvironment(request: request)
    }

    public func createEnvironment(request: CreateEnvironmentRequest) async throws
      -> GoogleLongrunning.Operation
    {
      try await self.createEnvironment(request: request, options: .init())
    }

    public func createEnvironment(
      request: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func createEnvironment(withPolling: CreateEnvironmentRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Environment>
    {
      try await self.createEnvironment(withPolling: withPolling, options: .init())
    }

    public func createEnvironment(
      withPolling: CreateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func createEnvironment(
      parent: Swift.String,
      environment: Environment?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
      let request = CreateEnvironmentRequest().with {
        $0.parent = parent
        $0.environment = environment
      }
      return try await self.createEnvironment(withPolling: request)
    }

    public func updateEnvironment(request: UpdateEnvironmentRequest) async throws
      -> GoogleLongrunning.Operation
    {
      try await self.updateEnvironment(request: request, options: .init())
    }

    public func updateEnvironment(
      request: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func updateEnvironment(withPolling: UpdateEnvironmentRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Environment>
    {
      try await self.updateEnvironment(withPolling: withPolling, options: .init())
    }

    public func updateEnvironment(
      withPolling: UpdateEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Environment>.State in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func updateEnvironment(
      environment: Environment?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Environment> {
      let request = UpdateEnvironmentRequest().with {
        $0.environment = environment
        $0.updateMask = updateMask
      }
      return try await self.updateEnvironment(withPolling: request)
    }

    public func deleteEnvironment(request: DeleteEnvironmentRequest) async throws {
      try await self.deleteEnvironment(request: request, options: .init())
    }

    public func deleteEnvironment(
      request: DeleteEnvironmentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func deleteEnvironment(
      name: Swift.String,
    ) async throws {
      let request = DeleteEnvironmentRequest().with {
        $0.name = name
      }
      try await self.deleteEnvironment(request: request)
    }

    public func lookupEnvironmentHistory(request: LookupEnvironmentHistoryRequest) async throws
      -> GoogleCloudDialogflowCxV3.LookupEnvironmentHistoryResponse
    {
      try await self.lookupEnvironmentHistory(request: request, options: .init())
    }

    public func lookupEnvironmentHistory(
      request: LookupEnvironmentHistoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCxV3.LookupEnvironmentHistoryResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func lookupEnvironmentHistory(
      byItem: LookupEnvironmentHistoryRequest
    ) throws -> any AsyncSequence<Environment, Swift.Error> {
      try self.lookupEnvironmentHistory(byItem: byItem, options: .init())
    }

    public func lookupEnvironmentHistory(
      byItem: LookupEnvironmentHistoryRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Environment, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws
          -> GoogleCloudDialogflowCxV3.LookupEnvironmentHistoryResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func lookupEnvironmentHistory(
      name: Swift.String,
    ) throws -> any AsyncSequence<Environment, Swift.Error> {
      let request = LookupEnvironmentHistoryRequest().with {
        $0.name = name
      }
      return try self.lookupEnvironmentHistory(byItem: request)
    }

    public func runContinuousTest(request: RunContinuousTestRequest) async throws
      -> GoogleLongrunning.Operation
    {
      try await self.runContinuousTest(request: request, options: .init())
    }

    public func runContinuousTest(
      request: RunContinuousTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func runContinuousTest(withPolling: RunContinuousTestRequest) async throws
      -> any GoogleCloudGax.PollableOperation<RunContinuousTestResponse>
    {
      try await self.runContinuousTest(withPolling: withPolling, options: .init())
    }

    public func runContinuousTest(
      withPolling: RunContinuousTestRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<RunContinuousTestResponse> {
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<RunContinuousTestResponse>.State in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func listContinuousTestResults(request: ListContinuousTestResultsRequest) async throws
      -> GoogleCloudDialogflowCxV3.ListContinuousTestResultsResponse
    {
      try await self.listContinuousTestResults(request: request, options: .init())
    }

    public func listContinuousTestResults(
      request: ListContinuousTestResultsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCxV3.ListContinuousTestResultsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listContinuousTestResults(
      byItem: ListContinuousTestResultsRequest
    ) throws -> any AsyncSequence<ContinuousTestResult, Swift.Error> {
      try self.listContinuousTestResults(byItem: byItem, options: .init())
    }

    public func listContinuousTestResults(
      byItem: ListContinuousTestResultsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ContinuousTestResult, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws
          -> GoogleCloudDialogflowCxV3.ListContinuousTestResultsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listContinuousTestResults(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ContinuousTestResult, Swift.Error> {
      let request = ListContinuousTestResultsRequest().with {
        $0.parent = parent
      }
      return try self.listContinuousTestResults(byItem: request)
    }

    public func deployFlow(request: DeployFlowRequest) async throws -> GoogleLongrunning.Operation {
      try await self.deployFlow(request: request, options: .init())
    }

    public func deployFlow(
      request: DeployFlowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func deployFlow(withPolling: DeployFlowRequest) async throws -> any GoogleCloudGax
      .PollableOperation<DeployFlowResponse>
    {
      try await self.deployFlow(withPolling: withPolling, options: .init())
    }

    public func deployFlow(
      withPolling: DeployFlowRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<DeployFlowResponse> {
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<DeployFlowResponse>.State in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse
    {
      try await self.listLocations(request: request, options: .init())
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      try self.listLocations(byItem: byItem, options: .init())
    }

    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location
    {
      try await self.getLocation(request: request, options: .init())
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      try self.listOperations(byItem: byItem, options: .init())
    }

    public func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let request = GoogleLongrunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return try self.listOperations(byItem: request)
    }

    public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
      -> GoogleLongrunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongrunning.Operation {
      let request = GoogleLongrunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongrunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }
  }
#endif
