// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Flows || Pages || Sessions || TestCases
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// An event handler specifies an
  /// [event][google.cloud.dialogflow.cx.v3.EventHandler.event] that can be handled
  /// during a session. When the specified event happens, the following actions are
  /// taken in order:
  ///
  /// *   If there is a
  /// [`trigger_fulfillment`][google.cloud.dialogflow.cx.v3.EventHandler.trigger_fulfillment]
  /// associated with the event, it will be called.
  /// *   If there is a
  /// [`target_page`][google.cloud.dialogflow.cx.v3.EventHandler.target_page]
  /// associated with the event, the session will transition into the specified
  /// page.
  /// *   If there is a
  /// [`target_flow`][google.cloud.dialogflow.cx.v3.EventHandler.target_flow]
  /// associated with the event, the session will transition into the specified
  /// flow.
  ///
  /// [google.cloud.dialogflow.cx.v3.EventHandler.event]: <doc:EventHandler/event>
  /// [google.cloud.dialogflow.cx.v3.EventHandler.target_flow]: <doc:EventHandler/OneOf_Target/targetFlow(_:)>
  /// [google.cloud.dialogflow.cx.v3.EventHandler.target_page]: <doc:EventHandler/OneOf_Target/targetPage(_:)>
  /// [google.cloud.dialogflow.cx.v3.EventHandler.trigger_fulfillment]: <doc:EventHandler/triggerFulfillment>
  public struct EventHandler: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The unique identifier of this event handler.
    public var name: Swift.String = Swift.String()

    /// Required. The name of the event to handle.
    public var event: Swift.String = Swift.String()

    /// The fulfillment to call when the event occurs.
    /// Handling webhook errors with a fulfillment enabled with webhook could
    /// cause infinite loop. It is invalid to specify such fulfillment for a
    /// handler handling webhooks.
    public var triggerFulfillment: Fulfillment? = nil

    /// The target to transition to, either a page in the same host flow (the flow
    /// that owns this
    /// [TransitionRoute][google.cloud.dialogflow.cx.v3.TransitionRoute]), or
    /// another flow in the same agent.
    ///
    /// [google.cloud.dialogflow.cx.v3.TransitionRoute]: <doc:TransitionRoute>
    public var target: OneOf_Target? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EventHandler`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EventHandler().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let event = CodingKeys(stringValue: "event")
      static let triggerFulfillment = CodingKeys(stringValue: "triggerFulfillment")
      static let targetPage = CodingKeys(stringValue: "targetPage")
      static let targetFlow = CodingKeys(stringValue: "targetFlow")
      static let targetPlaybook = CodingKeys(stringValue: "targetPlaybook")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "event",
        "triggerFulfillment",
        "targetPage",
        "targetFlow",
        "targetPlaybook",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .event) {
        self.event = value
      }
      self.triggerFulfillment = try container.decodeIfPresent(
        Fulfillment.self, forKey: .triggerFulfillment)

      var target: OneOf_Target? = nil
      let targetCheckAndSet = {
        if target != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'target'"))
        }
        target = $0
      }
      if let targetPage = try container.decodeIfPresent(Swift.String.self, forKey: .targetPage) {
        try targetCheckAndSet(.targetPage(targetPage))
      }
      if let targetFlow = try container.decodeIfPresent(Swift.String.self, forKey: .targetFlow) {
        try targetCheckAndSet(.targetFlow(targetFlow))
      }
      if let targetPlaybook = try container.decodeIfPresent(
        Swift.String.self, forKey: .targetPlaybook)
      {
        try targetCheckAndSet(.targetPlaybook(targetPlaybook))
      }
      self.target = target
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.event, forKey: .event)
      try container.encodeIfPresent(self.triggerFulfillment, forKey: .triggerFulfillment)

      if let choice = self.target {
        switch choice {
        case .targetPage(let value):
          try container.encode(value, forKey: .targetPage)
        case .targetFlow(let value):
          try container.encode(value, forKey: .targetFlow)
        case .targetPlaybook(let value):
          try container.encode(value, forKey: .targetPlaybook)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The target to transition to, either a page in the same host flow (the flow
    /// that owns this
    /// [TransitionRoute][google.cloud.dialogflow.cx.v3.TransitionRoute]), or
    /// another flow in the same agent.
    ///
    /// [google.cloud.dialogflow.cx.v3.TransitionRoute]: <doc:TransitionRoute>
    public enum OneOf_Target: Codable, Equatable, Sendable {
      /// The target page to transition to.
      /// Format:
      /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/flows/<FlowID>/pages/<PageID>`.
      case targetPage(Swift.String)
      /// The target flow to transition to.
      /// Format:
      /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/flows/<FlowID>`.
      case targetFlow(Swift.String)
      /// The target playbook to transition to.
      /// Format:
      /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/playbooks/<PlaybookID>`.
      case targetPlaybook(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.EventHandler"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
