// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Agents
  import Foundation
  import GoogleCloudWkt

  /// The request message for
  /// [Agents.ExportAgent][google.cloud.dialogflow.cx.v3.Agents.ExportAgent].
  ///
  /// [google.cloud.dialogflow.cx.v3.Agents.ExportAgent]: <doc:AgentsClient/exportAgent(request:)>
  public struct ExportAgentRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The name of the agent to export.
    /// Format: `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>`.
    public var name: Swift.String = Swift.String()

    /// Optional. The [Google Cloud
    /// Storage](https://cloud.google.com/storage/docs/) URI to export the agent
    /// to. The format of this URI must be `gs://<bucket-name>/<object-name>`. If
    /// left unspecified, the serialized agent is returned inline.
    ///
    /// Dialogflow performs a write operation for the Cloud Storage object
    /// on the caller's behalf, so your request authentication must
    /// have write permissions for the object. For more information, see
    /// [Dialogflow access
    /// control](https://cloud.google.com/dialogflow/cx/docs/concept/access-control#storage).
    public var agentUri: Swift.String = Swift.String()

    /// Optional. The data format of the exported agent. If not specified, `BLOB`
    /// is assumed.
    public var dataFormat: ExportAgentRequest.DataFormat = ExportAgentRequest.DataFormat()

    /// Optional. Environment name. If not set, draft environment is assumed.
    /// Format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/environments/<EnvironmentID>`.
    public var environment: Swift.String = Swift.String()

    /// Optional. The Git branch to export the agent to.
    public var gitDestination: ExportAgentRequest.GitDestination? = nil

    /// Optional. Whether to include BigQuery Export setting.
    public var includeBigqueryExportSettings: Swift.Bool = Swift.Bool()

    /// Initialize a new instance of `ExportAgentRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExportAgentRequest().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Settings for exporting to a git branch.
    public struct GitDestination: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Tracking branch for the git push.
      public var trackingBranch: Swift.String = Swift.String()

      /// Commit message for the git push.
      public var commitMessage: Swift.String = Swift.String()

      /// Initialize a new instance of `GitDestination`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GitDestination().with { $0.trackingBranch = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.dialogflow.cx.v3.ExportAgentRequest.GitDestination"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Data format of the exported agent.
    public enum DataFormat: Codable, Equatable, Sendable {
      /// Unspecified format.
      case unspecified
      /// Agent content will be exported as raw bytes.
      case blob
      /// Agent content will be exported in JSON Package format.
      case jsonPackage
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .blob: return 1
        case .jsonPackage: return 4
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "DATA_FORMAT_UNSPECIFIED"
        case .blob: return "BLOB"
        case .jsonPackage: return "JSON_PACKAGE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataFormat/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "DATA_FORMAT_UNSPECIFIED": self = .unspecified
        case "BLOB": self = .blob
        case "JSON_PACKAGE": self = .jsonPackage
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataFormat/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .blob
        case 4: self = .jsonPackage
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .blob: return try container.encode(1)
        case .jsonPackage: return try container.encode(4)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.ExportAgentRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
