// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TestCases
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// The request message for
  /// [TestCases.ExportTestCases][google.cloud.dialogflow.cx.v3.TestCases.ExportTestCases].
  ///
  /// [google.cloud.dialogflow.cx.v3.TestCases.ExportTestCases]: <doc:TestCasesClient/exportTestCases(request:options:)>
  public struct ExportTestCasesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The agent where to export test cases from.
    /// Format: `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>`.
    public var parent: Swift.String = Swift.String()

    /// The data format of the exported test cases. If not specified, `BLOB` is
    /// assumed.
    public var dataFormat: ExportTestCasesRequest.DataFormat = ExportTestCasesRequest.DataFormat()

    /// The filter expression used to filter exported test cases, see
    /// [API Filtering](https://aip.dev/160). The expression is case insensitive
    /// and supports the following syntax:
    ///
    ///   name = <value> [OR name = <value>] ...
    ///
    /// For example:
    ///
    /// *   "name = t1 OR name = t2" matches the test case with the exact resource
    ///     name "t1" or "t2".
    public var filter: Swift.String = Swift.String()

    /// The destination to export.
    public var destination: OneOf_Destination? = nil

    /// Initialize a new instance of `ExportTestCasesRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ExportTestCasesRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case parent = "parent"
      case gcsUri = "gcsUri"
      case dataFormat = "dataFormat"
      case filter = "filter"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.parent = try container.decode(Swift.String.self, forKey: .parent)
      self.dataFormat = try container.decode(
        ExportTestCasesRequest.DataFormat.self, forKey: .dataFormat)
      self.filter = try container.decode(Swift.String.self, forKey: .filter)

      var destination: OneOf_Destination? = nil
      let destinationCheckAndSet = {
        if destination != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'destination'"))
        }
        destination = $0
      }
      if let gcsUri = try container.decodeIfPresent(Swift.String.self, forKey: .gcsUri) {
        try destinationCheckAndSet(.gcsUri(gcsUri))
      }
      self.destination = destination
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parent, forKey: .parent)
      try container.encode(self.dataFormat, forKey: .dataFormat)
      try container.encode(self.filter, forKey: .filter)

      if let choice = self.destination {
        switch choice {
        case .gcsUri(let value):
          try container.encode(value, forKey: .gcsUri)
        }
      }
    }

    /// Data format of the exported test cases.
    public enum DataFormat: Codable, Equatable, Sendable {
      /// Unspecified format.
      case unspecified
      /// Raw bytes.
      case blob
      /// JSON format.
      case json
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .blob: return 1
        case .json: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "DATA_FORMAT_UNSPECIFIED"
        case .blob: return "BLOB"
        case .json: return "JSON"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DataFormat/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "DATA_FORMAT_UNSPECIFIED": self = .unspecified
        case "BLOB": self = .blob
        case "JSON": self = .json
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DataFormat/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .blob
        case 2: self = .json
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .blob: return try container.encode(1)
        case .json: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The destination to export.
    public enum OneOf_Destination: Codable, Equatable, Sendable {
      /// The [Google Cloud Storage](https://cloud.google.com/storage/docs/) URI to
      /// export the test cases to. The format of this URI must be
      /// `gs://<bucket-name>/<object-name>`. If unspecified, the serialized test
      /// cases is returned inline.
      ///
      /// Dialogflow performs a write operation for the Cloud Storage object
      /// on the caller's behalf, so your request authentication must
      /// have write permissions for the object. For more information, see
      /// [Dialogflow access
      /// control](https://cloud.google.com/dialogflow/cx/docs/concept/access-control#storage).
      case gcsUri(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.ExportTestCasesRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
