// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Flows
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleCloudLocation
  @_spi(GoogleCloudInternal) public import GoogleLongRunning
  @_spi(GoogleCloudInternal) public import GoogleWKT
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// Service for managing [Flows][google.cloud.dialogflow.cx.v3.Flow].
  ///
  /// [google.cloud.dialogflow.cx.v3.Flow]: <doc:Flow>
  ///
  /// @Snippet(path: "FlowsQuickstart")
  public final class FlowsClient: Clients.FlowsProtocol, Sendable {
    let inner: any Clients.FlowsStub
    let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
    let pollingBackoffPolicy: GoogleGax.BackoffPolicy

    /// Creates a new `FlowsClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.FlowsStub = try Clients.FlowsTransport(options)
      inner = Clients.FlowsRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.FlowsLogging(inner, logger: logger)
      }
      self.inner = inner
      self.pollingErrorPolicy = options.pollingErrorPolicy
      self.pollingBackoffPolicy = options.pollingBackoffPolicy
    }

    /// Creates a flow in the specified agent.
    ///
    /// Note: You should always train a flow prior to sending it queries. See the
    /// [training
    /// documentation](https://cloud.google.com/dialogflow/cx/docs/concept/training).
    ///
    /// @Snippet(path: "Flows_CreateFlow")
    public func createFlow(
      request: CreateFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Flow {
      try await self.inner.createFlow(request: request, options: options)
    }

    /// Deletes a specified flow.
    ///
    /// @Snippet(path: "Flows_DeleteFlow")
    public func deleteFlow(
      request: DeleteFlowRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.deleteFlow(request: request, options: options)
    }

    /// Returns the list of all flows in the specified agent.
    ///
    /// @Snippet(path: "Flows_ListFlows")
    public func listFlows(
      request: ListFlowsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.ListFlowsResponse {
      try await self.inner.listFlows(request: request, options: options)
    }

    /// Retrieves the specified flow.
    ///
    /// @Snippet(path: "Flows_GetFlow")
    public func getFlow(
      request: GetFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Flow {
      try await self.inner.getFlow(request: request, options: options)
    }

    /// Updates the specified flow.
    ///
    /// Note: You should always train a flow prior to sending it queries. See the
    /// [training
    /// documentation](https://cloud.google.com/dialogflow/cx/docs/concept/training).
    ///
    /// @Snippet(path: "Flows_UpdateFlow")
    public func updateFlow(
      request: UpdateFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Flow {
      try await self.inner.updateFlow(request: request, options: options)
    }

    /// Trains the specified flow. Note that only the flow in 'draft' environment
    /// is trained.
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`: An empty [Struct
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct)
    /// - `response`: An [Empty
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#empty)
    ///
    /// Note: You should always train a flow prior to sending it queries. See the
    /// [training
    /// documentation](https://cloud.google.com/dialogflow/cx/docs/concept/training).
    ///
    /// @Snippet(path: "Flows_TrainFlow")
    public func trainFlow(
      request: TrainFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.trainFlow(request: request, options: options)
    }

    /// Trains the specified flow. Note that only the flow in 'draft' environment
    /// is trained.
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`: An empty [Struct
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct)
    /// - `response`: An [Empty
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#empty)
    ///
    /// Note: You should always train a flow prior to sending it queries. See the
    /// [training
    /// documentation](https://cloud.google.com/dialogflow/cx/docs/concept/training).
    ///
    /// @Snippet(path: "Flows_TrainFlow")
    public func trainFlowPollingUntilDone(
      request: TrainFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        return try op._extractStatusEmpty()
      }
      let rawOp = try await self.trainFlow(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
    }

    /// Validates the specified flow and creates or updates validation results.
    /// Please call this API after the training is completed to get the complete
    /// validation results.
    ///
    /// @Snippet(path: "Flows_ValidateFlow")
    public func validateFlow(
      request: ValidateFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.FlowValidationResult {
      try await self.inner.validateFlow(request: request, options: options)
    }

    /// Gets the latest flow validation result. Flow validation is performed
    /// when ValidateFlow is called.
    ///
    /// @Snippet(path: "Flows_GetFlowValidationResult")
    public func getFlowValidationResult(
      request: GetFlowValidationResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.FlowValidationResult {
      try await self.inner.getFlowValidationResult(request: request, options: options)
    }

    /// Imports the specified flow to the specified agent from a binary file.
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`: An empty [Struct
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct)
    /// - `response`:
    /// [ImportFlowResponse][google.cloud.dialogflow.cx.v3.ImportFlowResponse]
    ///
    /// Note: You should always train a flow prior to sending it queries. See the
    /// [training
    /// documentation](https://cloud.google.com/dialogflow/cx/docs/concept/training).
    ///
    /// [google.cloud.dialogflow.cx.v3.ImportFlowResponse]: <doc:ImportFlowResponse>
    ///
    /// @Snippet(path: "Flows_ImportFlow")
    public func importFlow(
      request: ImportFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.importFlow(request: request, options: options)
    }

    /// Imports the specified flow to the specified agent from a binary file.
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`: An empty [Struct
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct)
    /// - `response`:
    /// [ImportFlowResponse][google.cloud.dialogflow.cx.v3.ImportFlowResponse]
    ///
    /// Note: You should always train a flow prior to sending it queries. See the
    /// [training
    /// documentation](https://cloud.google.com/dialogflow/cx/docs/concept/training).
    ///
    /// [google.cloud.dialogflow.cx.v3.ImportFlowResponse]: <doc:ImportFlowResponse>
    ///
    /// @Snippet(path: "Flows_ImportFlow")
    public func importFlowPollingUntilDone(
      request: ImportFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ImportFlowResponse> {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<ImportFlowResponse>.State in
        return try op._extractStatus(ImportFlowResponse.self)
      }
      let rawOp = try await self.importFlow(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<ImportFlowResponse>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
    }

    /// Exports the specified flow to a binary file.
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`: An empty [Struct
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct)
    /// - `response`:
    /// [ExportFlowResponse][google.cloud.dialogflow.cx.v3.ExportFlowResponse]
    ///
    /// Note that resources (e.g. intents, entities, webhooks) that the flow
    /// references will also be exported.
    ///
    /// [google.cloud.dialogflow.cx.v3.ExportFlowResponse]: <doc:ExportFlowResponse>
    ///
    /// @Snippet(path: "Flows_ExportFlow")
    public func exportFlow(
      request: ExportFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.exportFlow(request: request, options: options)
    }

    /// Exports the specified flow to a binary file.
    ///
    /// This method is a [long-running
    /// operation](https://cloud.google.com/dialogflow/cx/docs/how/long-running-operation).
    /// The returned `Operation` type has the following method-specific fields:
    ///
    /// - `metadata`: An empty [Struct
    ///   message](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#struct)
    /// - `response`:
    /// [ExportFlowResponse][google.cloud.dialogflow.cx.v3.ExportFlowResponse]
    ///
    /// Note that resources (e.g. intents, entities, webhooks) that the flow
    /// references will also be exported.
    ///
    /// [google.cloud.dialogflow.cx.v3.ExportFlowResponse]: <doc:ExportFlowResponse>
    ///
    /// @Snippet(path: "Flows_ExportFlow")
    public func exportFlowPollingUntilDone(
      request: ExportFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ExportFlowResponse> {
      let extractStatus = {
        @Sendable (op: GoogleLongRunning.Operation) throws
          -> GoogleGax._PollableOperationImpl<ExportFlowResponse>.State in
        return try op._extractStatus(ExportFlowResponse.self)
      }
      let rawOp = try await self.exportFlow(request: request, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<ExportFlowResponse>.State in
        let op = try await self.getOperation(
          request: .init().with { $0.name = rawOp.name }, options: options)
        return try extractStatus(op)
      }
      return GoogleGax._PollableOperationImpl(
        initialState: initialState,
        polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
        backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
        poll: poll,
      )
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "Flows_ListLocations")
    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Gets information about a location.
    ///
    /// @Snippet(path: "Flows_GetLocation")
    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Flows_ListOperations")
    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Flows_GetOperation")
    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Flows_CancelOperation")
    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `FlowsClient`.
    ///
    /// To mock `FlowsClient` change your functions to receive
    /// `some FlowsProtocol` or `any FlowsProtocol`
    /// and pass a mock implementation in your tests.
    public protocol FlowsProtocol: Sendable {
      /// See `FlowsClient.createFlow`.
      func createFlow(
        request: CreateFlowRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.Flow

      /// See `FlowsClient.deleteFlow`.
      func deleteFlow(
        request: DeleteFlowRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `FlowsClient.listFlows`.
      func listFlows(
        request: ListFlowsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.ListFlowsResponse

      /// See `FlowsClient.getFlow`.
      func getFlow(
        request: GetFlowRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.Flow

      /// See `FlowsClient.updateFlow`.
      func updateFlow(
        request: UpdateFlowRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.Flow

      /// See `FlowsClient.trainFlow`.
      func trainFlow(
        request: TrainFlowRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `FlowsClient.trainFlow`.
      func trainFlowPollingUntilDone(
        request: TrainFlowRequest, options: GoogleGax.RequestOptions
      ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

      /// See `FlowsClient.validateFlow`.
      func validateFlow(
        request: ValidateFlowRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.FlowValidationResult

      /// See `FlowsClient.getFlowValidationResult`.
      func getFlowValidationResult(
        request: GetFlowValidationResultRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.FlowValidationResult

      /// See `FlowsClient.importFlow`.
      func importFlow(
        request: ImportFlowRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `FlowsClient.importFlow`.
      func importFlowPollingUntilDone(
        request: ImportFlowRequest, options: GoogleGax.RequestOptions
      ) async throws -> any GoogleGax.PollableOperation<ImportFlowResponse>

      /// See `FlowsClient.exportFlow`.
      func exportFlow(
        request: ExportFlowRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation

      /// See `FlowsClient.exportFlow`.
      func exportFlowPollingUntilDone(
        request: ExportFlowRequest, options: GoogleGax.RequestOptions
      ) async throws -> any GoogleGax.PollableOperation<ExportFlowResponse>

      /// See `FlowsClient.listLocations`.
      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      /// See `FlowsClient.getLocation`.
      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      /// See `FlowsClient.listOperations`.
      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      /// See `FlowsClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws
    }
  }

  // Default implementations
  extension Clients.FlowsProtocol {
    public func createFlow(request: CreateFlowRequest) async throws
      -> GoogleCloudDialogflowCXV3.Flow
    {
      try await self.createFlow(request: request, options: .init())
    }

    public func createFlow(
      request: CreateFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Flow {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createFlow(
      parent: Swift.String,
      flow: Flow?,
    ) async throws -> GoogleCloudDialogflowCXV3.Flow {
      let request = CreateFlowRequest().with {
        $0.parent = parent
        $0.flow = flow
      }
      return try await self.createFlow(request: request)
    }

    public func deleteFlow(request: DeleteFlowRequest) async throws {
      try await self.deleteFlow(request: request, options: .init())
    }

    public func deleteFlow(
      request: DeleteFlowRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteFlow(
      name: Swift.String,
    ) async throws {
      let request = DeleteFlowRequest().with {
        $0.name = name
      }
      try await self.deleteFlow(request: request)
    }

    public func listFlows(request: ListFlowsRequest) async throws
      -> GoogleCloudDialogflowCXV3.ListFlowsResponse
    {
      try await self.listFlows(request: request, options: .init())
    }

    public func listFlows(
      request: ListFlowsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.ListFlowsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listFlowsByItems(
      request: ListFlowsRequest
    ) -> some AsyncSequence<Flow, Swift.Error> & Sendable {
      self.listFlowsByItems(request: request, options: .init())
    }

    /// Returns the list of all flows in the specified agent.
    ///
    /// @Snippet(path: "Flows_ListFlows")
    public func listFlowsByItems(
      request: ListFlowsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<Flow, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleCloudDialogflowCXV3.ListFlowsResponse
        in
        var request = request
        request.pageToken = token
        return try await self.listFlows(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listFlowsByItems(
      parent: Swift.String,
    ) -> some AsyncSequence<Flow, Swift.Error> & Sendable {
      let request = ListFlowsRequest().with {
        $0.parent = parent
      }
      return self.listFlowsByItems(request: request)
    }

    public func getFlow(request: GetFlowRequest) async throws -> GoogleCloudDialogflowCXV3.Flow {
      try await self.getFlow(request: request, options: .init())
    }

    public func getFlow(
      request: GetFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Flow {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getFlow(
      name: Swift.String,
    ) async throws -> GoogleCloudDialogflowCXV3.Flow {
      let request = GetFlowRequest().with {
        $0.name = name
      }
      return try await self.getFlow(request: request)
    }

    public func updateFlow(request: UpdateFlowRequest) async throws
      -> GoogleCloudDialogflowCXV3.Flow
    {
      try await self.updateFlow(request: request, options: .init())
    }

    public func updateFlow(
      request: UpdateFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Flow {
      throw GoogleGax.RequestError.unimplemented
    }

    public func updateFlow(
      flow: Flow?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> GoogleCloudDialogflowCXV3.Flow {
      let request = UpdateFlowRequest().with {
        $0.flow = flow
        $0.updateMask = updateMask
      }
      return try await self.updateFlow(request: request)
    }

    public func trainFlow(request: TrainFlowRequest) async throws -> GoogleLongRunning.Operation {
      try await self.trainFlow(request: request, options: .init())
    }

    public func trainFlow(
      request: TrainFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func trainFlowPollingUntilDone(request: TrainFlowRequest) async throws -> any GoogleGax
      .PollableOperation<Swift.Void>
    {
      try await self.trainFlowPollingUntilDone(request: request, options: .init())
    }

    public func trainFlowPollingUntilDone(
      request: TrainFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
        throw GoogleGax.RequestError.unimplemented
      }
      return GoogleGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func trainFlowPollingUntilDone(
      name: Swift.String,
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
      let request = TrainFlowRequest().with {
        $0.name = name
      }
      return try await self.trainFlowPollingUntilDone(request: request)
    }

    public func validateFlow(request: ValidateFlowRequest) async throws
      -> GoogleCloudDialogflowCXV3.FlowValidationResult
    {
      try await self.validateFlow(request: request, options: .init())
    }

    public func validateFlow(
      request: ValidateFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.FlowValidationResult {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getFlowValidationResult(request: GetFlowValidationResultRequest) async throws
      -> GoogleCloudDialogflowCXV3.FlowValidationResult
    {
      try await self.getFlowValidationResult(request: request, options: .init())
    }

    public func getFlowValidationResult(
      request: GetFlowValidationResultRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.FlowValidationResult {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getFlowValidationResult(
      name: Swift.String,
    ) async throws -> GoogleCloudDialogflowCXV3.FlowValidationResult {
      let request = GetFlowValidationResultRequest().with {
        $0.name = name
      }
      return try await self.getFlowValidationResult(request: request)
    }

    public func importFlow(request: ImportFlowRequest) async throws -> GoogleLongRunning.Operation {
      try await self.importFlow(request: request, options: .init())
    }

    public func importFlow(
      request: ImportFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func importFlowPollingUntilDone(request: ImportFlowRequest) async throws -> any GoogleGax
      .PollableOperation<ImportFlowResponse>
    {
      try await self.importFlowPollingUntilDone(request: request, options: .init())
    }

    public func importFlowPollingUntilDone(
      request: ImportFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ImportFlowResponse> {
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<ImportFlowResponse>.State in
        throw GoogleGax.RequestError.unimplemented
      }
      return GoogleGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func exportFlow(request: ExportFlowRequest) async throws -> GoogleLongRunning.Operation {
      try await self.exportFlow(request: request, options: .init())
    }

    public func exportFlow(
      request: ExportFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func exportFlowPollingUntilDone(request: ExportFlowRequest) async throws -> any GoogleGax
      .PollableOperation<ExportFlowResponse>
    {
      try await self.exportFlowPollingUntilDone(request: request, options: .init())
    }

    public func exportFlowPollingUntilDone(
      request: ExportFlowRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<ExportFlowResponse> {
      let poll = {
        @Sendable () async throws -> GoogleGax._PollableOperationImpl<ExportFlowResponse>.State in
        throw GoogleGax.RequestError.unimplemented
      }
      return GoogleGax._PollableOperationImpl(
        initialState: .init(done: false, result: nil), poll: poll)
    }

    public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse
    {
      try await self.listLocations(request: request, options: .init())
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listLocationsByItems(
      request: GoogleCloudLocation.ListLocationsRequest
    ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
      self.listLocationsByItems(request: request, options: .init())
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "Flows_ListLocations")
    public func listLocationsByItems(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location
    {
      try await self.getLocation(request: request, options: .init())
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest
    ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      self.listOperationsByItems(request: request, options: .init())
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Flows_ListOperations")
    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listOperationsByItems(
      name: Swift.String,
      filter: Swift.String,
    ) -> some AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      let request = GoogleLongRunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return self.listOperationsByItems(request: request)
    }

    public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongRunning.Operation {
      let request = GoogleLongRunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable, message: "Enable the 'Flows' trait in Package.swift to use this client."
  )
  public final class FlowsClient: Sendable {
    @available(
      *, unavailable, message: "Enable the 'Flows' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
