// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Sessions
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Request of [FulfillIntent][]
  public struct FulfillIntentRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Must be same as the corresponding MatchIntent request, otherwise the
    /// behavior is undefined.
    public var matchIntentRequest: MatchIntentRequest? = nil

    /// The matched intent/event to fulfill.
    public var match: Match? = nil

    /// Instructs the speech synthesizer how to generate output audio.
    public var outputAudioConfig: OutputAudioConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `FulfillIntentRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FulfillIntentRequest().with { $0.matchIntentRequest = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let matchIntentRequest = CodingKeys(stringValue: "matchIntentRequest")
      static let match = CodingKeys(stringValue: "match")
      static let outputAudioConfig = CodingKeys(stringValue: "outputAudioConfig")

      static let _knownKeys: Set<Swift.String> = [
        "matchIntentRequest",
        "match",
        "outputAudioConfig",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.matchIntentRequest = try container.decodeIfPresent(
        MatchIntentRequest.self, forKey: .matchIntentRequest)
      self.match = try container.decodeIfPresent(Match.self, forKey: .match)
      self.outputAudioConfig = try container.decodeIfPresent(
        OutputAudioConfig.self, forKey: .outputAudioConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.matchIntentRequest, forKey: .matchIntentRequest)
      try container.encodeIfPresent(self.match, forKey: .match)
      try container.encodeIfPresent(self.outputAudioConfig, forKey: .outputAudioConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.FulfillIntentRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
