// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if EntityTypes
  import Foundation
  import GoogleCloudWkt

  /// The request message for
  /// [EntityTypes.ImportEntityTypes][google.cloud.dialogflow.cx.v3.EntityTypes.ImportEntityTypes].
  ///
  /// [google.cloud.dialogflow.cx.v3.EntityTypes.ImportEntityTypes]: <doc:EntityTypesClient/importEntityTypes(request:)>
  public struct ImportEntityTypesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The agent to import the entity types into.
    /// Format: `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>`.
    public var parent: Swift.String = Swift.String()

    /// Required. Merge option for importing entity types.
    public var mergeOption: ImportEntityTypesRequest.MergeOption =
      ImportEntityTypesRequest.MergeOption()

    /// Optional. The target entity type to import into.
    /// Format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/entity_types/<EntityTypeID>`.
    /// If set, there should be only one entity type included in
    /// [entity_types][google.cloud.dialogflow.cx.v3.ImportEntityTypesRequest.entity_types],
    /// of which the type should match the type of the target entity type. All
    /// [entities][google.cloud.dialogflow.cx.v3.EntityType.entities] in the
    /// imported entity type will be added to the target entity type.
    ///
    /// [google.cloud.dialogflow.cx.v3.EntityType.entities]: <doc:EntityType/entities>
    /// [google.cloud.dialogflow.cx.v3.ImportEntityTypesRequest.entity_types]: <doc:ImportEntityTypesRequest/OneOf_EntityTypes>
    public var targetEntityType: Swift.String = Swift.String()

    /// Required. The entity types to import.
    public var entityTypes: OneOf_EntityTypes? = nil

    /// Initialize a new instance of `ImportEntityTypesRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImportEntityTypesRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case parent = "parent"
      case entityTypesUri = "entityTypesUri"
      case entityTypesContent = "entityTypesContent"
      case mergeOption = "mergeOption"
      case targetEntityType = "targetEntityType"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.parent = try container.decode(Swift.String.self, forKey: .parent)
      self.mergeOption = try container.decode(
        ImportEntityTypesRequest.MergeOption.self, forKey: .mergeOption)
      self.targetEntityType = try container.decode(Swift.String.self, forKey: .targetEntityType)

      var entityTypes: OneOf_EntityTypes? = nil
      let entityTypesCheckAndSet = {
        if entityTypes != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'entityTypes'"))
        }
        entityTypes = $0
      }
      if let entityTypesUri = try container.decodeIfPresent(
        Swift.String.self, forKey: .entityTypesUri)
      {
        try entityTypesCheckAndSet(.entityTypesUri(entityTypesUri))
      }
      if let entityTypesContent = try container.decodeIfPresent(
        InlineSource?.self, forKey: .entityTypesContent)
      {
        try entityTypesCheckAndSet(.entityTypesContent(entityTypesContent))
      }
      self.entityTypes = entityTypes
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parent, forKey: .parent)
      try container.encode(self.mergeOption, forKey: .mergeOption)
      try container.encode(self.targetEntityType, forKey: .targetEntityType)

      if let choice = self.entityTypes {
        switch choice {
        case .entityTypesUri(let value):
          try container.encode(value, forKey: .entityTypesUri)
        case .entityTypesContent(let value):
          try container.encode(value, forKey: .entityTypesContent)
        }
      }
    }

    /// Merge option when display name conflicts exist during import.
    public enum MergeOption: Codable, Equatable, Sendable {
      /// Unspecified. If used, system uses REPORT_CONFLICT as default.
      case unspecified
      /// Replace the original entity type in the agent with the new entity type
      /// when display name conflicts exist.
      case replace
      /// Merge the original entity type with the new entity type when display name
      /// conflicts exist.
      case merge
      /// Create new entity types with new display names to differentiate them from
      /// the existing entity types when display name conflicts exist.
      case rename
      /// Report conflict information if display names conflict is detected.
      /// Otherwise, import entity types.
      case reportConflict
      /// Keep the original entity type and discard the conflicting new entity type
      /// when display name conflicts exist.
      case keep
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .replace: return 1
        case .merge: return 2
        case .rename: return 3
        case .reportConflict: return 4
        case .keep: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "MERGE_OPTION_UNSPECIFIED"
        case .replace: return "REPLACE"
        case .merge: return "MERGE"
        case .rename: return "RENAME"
        case .reportConflict: return "REPORT_CONFLICT"
        case .keep: return "KEEP"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MergeOption/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "MERGE_OPTION_UNSPECIFIED": self = .unspecified
        case "REPLACE": self = .replace
        case "MERGE": self = .merge
        case "RENAME": self = .rename
        case "REPORT_CONFLICT": self = .reportConflict
        case "KEEP": self = .keep
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MergeOption/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .replace
        case 2: self = .merge
        case 3: self = .rename
        case 4: self = .reportConflict
        case 5: self = .keep
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .replace: return try container.encode(1)
        case .merge: return try container.encode(2)
        case .rename: return try container.encode(3)
        case .reportConflict: return try container.encode(4)
        case .keep: return try container.encode(5)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Required. The entity types to import.
    public enum OneOf_EntityTypes: Codable, Equatable, Sendable {
      /// The [Google Cloud Storage](https://cloud.google.com/storage/docs/) URI
      /// to import entity types from. The format of this URI must be
      /// `gs://<bucket-name>/<object-name>`.
      ///
      /// Dialogflow performs a read operation for the Cloud Storage object
      /// on the caller's behalf, so your request authentication must
      /// have read permissions for the object. For more information, see
      /// [Dialogflow access
      /// control](https://cloud.google.com/dialogflow/cx/docs/concept/access-control#storage).
      case entityTypesUri(Swift.String)
      /// Uncompressed byte content of entity types.
      indirect case entityTypesContent(InlineSource?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.ImportEntityTypesRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
