// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Playbooks
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// The response message for
  /// [Playbooks.ImportPlaybook][google.cloud.dialogflow.cx.v3.Playbooks.ImportPlaybook].
  ///
  /// [google.cloud.dialogflow.cx.v3.Playbooks.ImportPlaybook]: <doc:PlaybooksClient/importPlaybook(request:options:)>
  public struct ImportPlaybookResponse: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The unique identifier of the new playbook.
    /// Format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/playbooks/<PlaybookID>`.
    public var playbook: Swift.String = Swift.String()

    /// Info which resources have conflicts when
    /// [REPORT_CONFLICTS][ImportPlaybookResponse.REPORT_CONFLICTS] import strategy
    /// is set for all resources in ImportPlaybookRequest.
    public var conflictingResources: ImportPlaybookResponse.ConflictingResources? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ImportPlaybookResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ImportPlaybookResponse().with { $0.playbook = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let playbook = CodingKeys(stringValue: "playbook")
      static let conflictingResources = CodingKeys(stringValue: "conflictingResources")

      static let _knownKeys: Set<Swift.String> = [
        "playbook",
        "conflictingResources",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .playbook) {
        self.playbook = value
      }
      self.conflictingResources = try container.decodeIfPresent(
        ImportPlaybookResponse.ConflictingResources.self, forKey: .conflictingResources)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.playbook, forKey: .playbook)
      try container.encodeIfPresent(self.conflictingResources, forKey: .conflictingResources)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Conflicting resources detected during the import process. Only filled when
    /// [REPORT_CONFLICTS][ImportPlaybookResponse.REPORT_CONFLICTS] is set in the
    /// request and there are conflicts in the display names.
    public struct ConflictingResources: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Display name of conflicting main playbook.
      public var mainPlaybookDisplayName: Swift.String = Swift.String()

      /// Display names of conflicting nested playbooks.
      public var nestedPlaybookDisplayNames: [Swift.String] = []

      /// Display names of conflicting tools.
      public var toolDisplayNames: [Swift.String] = []

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ConflictingResources`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ConflictingResources().with { $0.mainPlaybookDisplayName = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let mainPlaybookDisplayName = CodingKeys(stringValue: "mainPlaybookDisplayName")
        static let nestedPlaybookDisplayNames = CodingKeys(
          stringValue: "nestedPlaybookDisplayNames")
        static let toolDisplayNames = CodingKeys(stringValue: "toolDisplayNames")

        static let _knownKeys: Set<Swift.String> = [
          "mainPlaybookDisplayName",
          "nestedPlaybookDisplayNames",
          "toolDisplayNames",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(
          Swift.String.self, forKey: .mainPlaybookDisplayName)
        {
          self.mainPlaybookDisplayName = value
        }
        if let value = try container.decodeIfPresent(
          [Swift.String].self, forKey: .nestedPlaybookDisplayNames)
        {
          self.nestedPlaybookDisplayNames = value
        }
        if let value = try container.decodeIfPresent([Swift.String].self, forKey: .toolDisplayNames)
        {
          self.toolDisplayNames = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.mainPlaybookDisplayName, forKey: .mainPlaybookDisplayName)
        try container.encode(self.nestedPlaybookDisplayNames, forKey: .nestedPlaybookDisplayNames)
        try container.encode(self.toolDisplayNames, forKey: .toolDisplayNames)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dialogflow.cx.v3.ImportPlaybookResponse.ConflictingResources"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.ImportPlaybookResponse"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
