// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Intents || Sessions || TestCases
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// An intent represents a user's intent to interact with a conversational agent.
  ///
  /// You can provide information for the Dialogflow API to use to match user input
  /// to an intent by adding training phrases (i.e., examples of user input) to
  /// your intent.
  public struct Intent: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The unique identifier of the intent.
    /// Required for the
    /// [Intents.UpdateIntent][google.cloud.dialogflow.cx.v3.Intents.UpdateIntent]
    /// method.
    /// [Intents.CreateIntent][google.cloud.dialogflow.cx.v3.Intents.CreateIntent]
    /// populates the name automatically.
    /// Format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/intents/<IntentID>`.
    ///
    /// [google.cloud.dialogflow.cx.v3.Intents.CreateIntent]: <doc:IntentsClient/createIntent(request:options:)>
    /// [google.cloud.dialogflow.cx.v3.Intents.UpdateIntent]: <doc:IntentsClient/updateIntent(request:options:)>
    public var name: Swift.String = Swift.String()

    /// Required. The human-readable name of the intent, unique within the agent.
    public var displayName: Swift.String = Swift.String()

    /// The collection of training phrases the agent is trained on to identify the
    /// intent.
    public var trainingPhrases: [Intent.TrainingPhrase] = []

    /// The collection of parameters associated with the intent.
    public var parameters: [Intent.Parameter] = []

    /// The priority of this intent. Higher numbers represent higher
    /// priorities.
    ///
    /// - If the supplied value is unspecified or 0, the service
    ///   translates the value to 500,000, which corresponds to the
    ///   `Normal` priority in the console.
    /// - If the supplied value is negative, the intent is ignored
    ///   in runtime detect intent requests.
    public var priority: Swift.Int32 = Swift.Int32()

    /// Indicates whether this is a fallback intent. Currently only default
    /// fallback intent is allowed in the agent, which is added upon agent
    /// creation.
    /// Adding training phrases to fallback intent is useful in the case of
    /// requests that are mistakenly matched, since training phrases assigned to
    /// fallback intents act as negative examples that triggers no-match event.
    public var isFallback: Swift.Bool = Swift.Bool()

    /// The key/value metadata to label an intent. Labels can contain
    /// lowercase letters, digits and the symbols '-' and '_'. International
    /// characters are allowed, including letters from unicase alphabets. Keys must
    /// start with a letter. Keys and values can be no longer than 63 characters
    /// and no more than 128 bytes.
    ///
    /// Prefix "sys-" is reserved for Dialogflow defined labels. Currently allowed
    /// Dialogflow defined labels include:
    /// * sys-head
    /// * sys-contextual
    /// The above labels do not require value. "sys-head" means the intent is a
    /// head intent. "sys.contextual" means the intent is a contextual intent.
    public var labels: [Swift.String: Swift.String] = [:]

    /// Human readable description for better understanding an intent like its
    /// scope, content, result etc. Maximum character limit: 140 characters.
    public var description: Swift.String = Swift.String()

    /// Optional. Matching DTMF pattern for the intent.
    public var dtmfPattern: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Intent`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Intent().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let displayName = CodingKeys(stringValue: "displayName")
      static let trainingPhrases = CodingKeys(stringValue: "trainingPhrases")
      static let parameters = CodingKeys(stringValue: "parameters")
      static let priority = CodingKeys(stringValue: "priority")
      static let isFallback = CodingKeys(stringValue: "isFallback")
      static let labels = CodingKeys(stringValue: "labels")
      static let description = CodingKeys(stringValue: "description")
      static let dtmfPattern = CodingKeys(stringValue: "dtmfPattern")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "displayName",
        "trainingPhrases",
        "parameters",
        "priority",
        "isFallback",
        "labels",
        "description",
        "dtmfPattern",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
        self.displayName = value
      }
      if let value = try container.decodeIfPresent(
        [Intent.TrainingPhrase].self, forKey: .trainingPhrases)
      {
        self.trainingPhrases = value
      }
      if let value = try container.decodeIfPresent([Intent.Parameter].self, forKey: .parameters) {
        self.parameters = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .priority) {
        self.priority = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isFallback) {
        self.isFallback = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .labels)
      {
        self.labels = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dtmfPattern) {
        self.dtmfPattern = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.displayName, forKey: .displayName)
      try container.encode(self.trainingPhrases, forKey: .trainingPhrases)
      try container.encode(self.parameters, forKey: .parameters)
      try container.encode(self.priority, forKey: .priority)
      try container.encode(self.isFallback, forKey: .isFallback)
      try container.encode(self.labels, forKey: .labels)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.dtmfPattern, forKey: .dtmfPattern)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Represents an example that the agent is trained on to identify the intent.
    public struct TrainingPhrase: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Output only. The unique identifier of the training phrase.
      public var id: Swift.String = Swift.String()

      /// Required. The ordered list of training phrase parts.
      /// The parts are concatenated in order to form the training phrase.
      ///
      /// Note: The API does not automatically annotate training phrases like the
      /// Dialogflow Console does.
      ///
      /// Note: Do not forget to include whitespace at part boundaries, so the
      /// training phrase is well formatted when the parts are concatenated.
      ///
      /// If the training phrase does not need to be annotated with parameters,
      /// you just need a single part with only the
      /// [Part.text][google.cloud.dialogflow.cx.v3.Intent.TrainingPhrase.Part.text]
      /// field set.
      ///
      /// If you want to annotate the training phrase, you must create multiple
      /// parts, where the fields of each part are populated in one of two ways:
      ///
      /// -   `Part.text` is set to a part of the phrase that has no parameters.
      /// -   `Part.text` is set to a part of the phrase that you want to annotate,
      ///     and the `parameter_id` field is set.
      ///
      /// [google.cloud.dialogflow.cx.v3.Intent.TrainingPhrase.Part.text]: <doc:Intent/TrainingPhrase/Part/text>
      public var parts: [Intent.TrainingPhrase.Part] = []

      /// Indicates how many times this example was added to the intent.
      public var repeatCount: Swift.Int32 = Swift.Int32()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `TrainingPhrase`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = TrainingPhrase().with { $0.id = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let id = CodingKeys(stringValue: "id")
        static let parts = CodingKeys(stringValue: "parts")
        static let repeatCount = CodingKeys(stringValue: "repeatCount")

        static let _knownKeys: Set<Swift.String> = [
          "id",
          "parts",
          "repeatCount",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
          self.id = value
        }
        if let value = try container.decodeIfPresent(
          [Intent.TrainingPhrase.Part].self, forKey: .parts)
        {
          self.parts = value
        }
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .repeatCount) {
          self.repeatCount = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.parts, forKey: .parts)
        try container.encode(self.repeatCount, forKey: .repeatCount)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      /// Represents a part of a training phrase.
      public struct Part: Codable, Equatable, GoogleWKT._AnyPackable,
        Sendable
      {
        /// Required. The text for this part.
        public var text: Swift.String = Swift.String()

        /// The [parameter][google.cloud.dialogflow.cx.v3.Intent.Parameter] used to
        /// annotate this part of the training phrase. This field is required for
        /// annotated parts of the training phrase.
        ///
        /// [google.cloud.dialogflow.cx.v3.Intent.Parameter]: <doc:Intent/Parameter>
        public var parameterId: Swift.String = Swift.String()

        @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

        /// Initialize a new instance of `Part`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = Part().with { $0.text = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private struct CodingKeys: CodingKey {
          var stringValue: Swift.String
          var intValue: Swift.Int? { nil }
          init(stringValue: Swift.String) { self.stringValue = stringValue }
          init?(intValue: Swift.Int) { nil }

          static let text = CodingKeys(stringValue: "text")
          static let parameterId = CodingKeys(stringValue: "parameterId")

          static let _knownKeys: Set<Swift.String> = [
            "text",
            "parameterId",
          ]
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          if let value = try container.decodeIfPresent(Swift.String.self, forKey: .text) {
            self.text = value
          }
          if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parameterId) {
            self.parameterId = value
          }
          for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
            self._unknownFields.json[key.stringValue] = try container.decode(
              GoogleWKT.Value.self, forKey: key)
          }
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.text, forKey: .text)
          try container.encode(self.parameterId, forKey: .parameterId)
          for (key, value) in self._unknownFields.json {
            try container.encode(value, forKey: CodingKeys(stringValue: key))
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return "type.googleapis.com/google.cloud.dialogflow.cx.v3.Intent.TrainingPhrase.Part"
        }
        public init(fromAny any: GoogleWKT.`Any`) throws {
          self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleWKT.Struct {
          return try GoogleWKT._slowAnySerialize(message: self)
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.dialogflow.cx.v3.Intent.TrainingPhrase"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Represents an intent parameter.
    public struct Parameter: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Required. The unique identifier of the parameter. This field
      /// is used by [training
      /// phrases][google.cloud.dialogflow.cx.v3.Intent.TrainingPhrase] to annotate
      /// their [parts][google.cloud.dialogflow.cx.v3.Intent.TrainingPhrase.Part].
      ///
      /// [google.cloud.dialogflow.cx.v3.Intent.TrainingPhrase]: <doc:Intent/TrainingPhrase>
      /// [google.cloud.dialogflow.cx.v3.Intent.TrainingPhrase.Part]: <doc:Intent/TrainingPhrase/Part>
      public var id: Swift.String = Swift.String()

      /// Required. The entity type of the parameter.
      /// Format:
      /// `projects/-/locations/-/agents/-/entityTypes/<SystemEntityTypeID>` for
      /// system entity types (for example,
      /// `projects/-/locations/-/agents/-/entityTypes/sys.date`), or
      /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/entityTypes/<EntityTypeID>`
      /// for developer entity types.
      public var entityType: Swift.String = Swift.String()

      /// Indicates whether the parameter represents a list of values.
      public var isList: Swift.Bool = Swift.Bool()

      /// Indicates whether the parameter content should be redacted in log. If
      /// redaction is enabled, the parameter content will be replaced by parameter
      /// name during logging.
      /// Note: the parameter content is subject to redaction if either parameter
      /// level redaction or [entity type level
      /// redaction][google.cloud.dialogflow.cx.v3.EntityType.redact] is enabled.
      ///
      /// [google.cloud.dialogflow.cx.v3.EntityType.redact]: <doc:EntityType/redact>
      public var redact: Swift.Bool = Swift.Bool()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Parameter`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Parameter().with { $0.id = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let id = CodingKeys(stringValue: "id")
        static let entityType = CodingKeys(stringValue: "entityType")
        static let isList = CodingKeys(stringValue: "isList")
        static let redact = CodingKeys(stringValue: "redact")

        static let _knownKeys: Set<Swift.String> = [
          "id",
          "entityType",
          "isList",
          "redact",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .id) {
          self.id = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .entityType) {
          self.entityType = value
        }
        if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isList) {
          self.isList = value
        }
        if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .redact) {
          self.redact = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.id, forKey: .id)
        try container.encode(self.entityType, forKey: .entityType)
        try container.encode(self.isList, forKey: .isList)
        try container.encode(self.redact, forKey: .redact)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.dialogflow.cx.v3.Intent.Parameter"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.Intent"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
