// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Flows || Pages || Sessions || TestCases
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// The Knowledge Connector settings for this page or flow.
  /// This includes information such as the attached Knowledge Bases, and the way
  /// to execute fulfillment.
  public struct KnowledgeConnectorSettings: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Whether Knowledge Connector is enabled or not.
    public var enabled: Swift.Bool = Swift.Bool()

    /// The fulfillment to be triggered.
    ///
    /// When the answers from the Knowledge Connector are selected by Dialogflow,
    /// you can utitlize the request scoped parameter `$request.knowledge.answers`
    /// (contains up to the 5 highest confidence answers) and
    /// `$request.knowledge.questions` (contains the corresponding questions) to
    /// construct the fulfillment.
    public var triggerFulfillment: Fulfillment? = nil

    /// Optional. List of related data store connections.
    public var dataStoreConnections: [DataStoreConnection] = []

    /// The target to transition to, either a page in the same host flow (the flow
    /// that owns this
    /// [KnowledgeConnectorSettings][google.cloud.dialogflow.cx.v3.KnowledgeConnectorSettings]),
    /// or another flow in the same agent.
    ///
    /// [google.cloud.dialogflow.cx.v3.KnowledgeConnectorSettings]: <doc:KnowledgeConnectorSettings>
    public var target: OneOf_Target? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `KnowledgeConnectorSettings`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = KnowledgeConnectorSettings().with { $0.enabled = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let enabled = CodingKeys(stringValue: "enabled")
      static let triggerFulfillment = CodingKeys(stringValue: "triggerFulfillment")
      static let targetPage = CodingKeys(stringValue: "targetPage")
      static let targetFlow = CodingKeys(stringValue: "targetFlow")
      static let dataStoreConnections = CodingKeys(stringValue: "dataStoreConnections")

      static let _knownKeys: Set<Swift.String> = [
        "enabled",
        "triggerFulfillment",
        "targetPage",
        "targetFlow",
        "dataStoreConnections",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enabled) {
        self.enabled = value
      }
      self.triggerFulfillment = try container.decodeIfPresent(
        Fulfillment.self, forKey: .triggerFulfillment)
      if let value = try container.decodeIfPresent(
        [DataStoreConnection].self, forKey: .dataStoreConnections)
      {
        self.dataStoreConnections = value
      }

      var target: OneOf_Target? = nil
      let targetCheckAndSet = {
        if target != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'target'"))
        }
        target = $0
      }
      if let targetPage = try container.decodeIfPresent(Swift.String.self, forKey: .targetPage) {
        try targetCheckAndSet(.targetPage(targetPage))
      }
      if let targetFlow = try container.decodeIfPresent(Swift.String.self, forKey: .targetFlow) {
        try targetCheckAndSet(.targetFlow(targetFlow))
      }
      self.target = target
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.enabled, forKey: .enabled)
      try container.encodeIfPresent(self.triggerFulfillment, forKey: .triggerFulfillment)
      try container.encode(self.dataStoreConnections, forKey: .dataStoreConnections)

      if let choice = self.target {
        switch choice {
        case .targetPage(let value):
          try container.encode(value, forKey: .targetPage)
        case .targetFlow(let value):
          try container.encode(value, forKey: .targetFlow)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The target to transition to, either a page in the same host flow (the flow
    /// that owns this
    /// [KnowledgeConnectorSettings][google.cloud.dialogflow.cx.v3.KnowledgeConnectorSettings]),
    /// or another flow in the same agent.
    ///
    /// [google.cloud.dialogflow.cx.v3.KnowledgeConnectorSettings]: <doc:KnowledgeConnectorSettings>
    public enum OneOf_Target: Codable, Equatable, Sendable {
      /// The target page to transition to.
      /// Format:
      /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/flows/<FlowID>/pages/<PageID>`.
      case targetPage(Swift.String)
      /// The target flow to transition to.
      /// Format:
      /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/flows/<FlowID>`.
      case targetFlow(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.KnowledgeConnectorSettings"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
