// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Agents && Changelogs && Deployments && EntityTypes && Environments && Examples && Experiments && Flows && Generators && Intents && Pages && Playbooks && SecuritySettingsService && SessionEntityTypes && Sessions && TestCases && Tools && TransitionRouteGroups && Versions && Webhooks
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Represents the language information of the request.
  public struct LanguageInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The language code specified in the original
    /// [request][google.cloud.dialogflow.cx.v3.QueryInput.language_code].
    ///
    /// [google.cloud.dialogflow.cx.v3.QueryInput.language_code]: <doc:QueryInput/languageCode>
    public var inputLanguageCode: Swift.String = Swift.String()

    /// The language code detected for this request based on the user
    /// conversation.
    public var resolvedLanguageCode: Swift.String = Swift.String()

    /// The confidence score of the detected language between 0 and 1.
    public var confidenceScore: Swift.Float = Swift.Float()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LanguageInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LanguageInfo().with { $0.inputLanguageCode = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let inputLanguageCode = CodingKeys(stringValue: "inputLanguageCode")
      static let resolvedLanguageCode = CodingKeys(stringValue: "resolvedLanguageCode")
      static let confidenceScore = CodingKeys(stringValue: "confidenceScore")

      static let _knownKeys: Set<Swift.String> = [
        "inputLanguageCode",
        "resolvedLanguageCode",
        "confidenceScore",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputLanguageCode) {
        self.inputLanguageCode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .resolvedLanguageCode)
      {
        self.resolvedLanguageCode = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidenceScore) {
        self.confidenceScore = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.inputLanguageCode, forKey: .inputLanguageCode)
      try container.encode(self.resolvedLanguageCode, forKey: .resolvedLanguageCode)
      try container.encode(self.confidenceScore, forKey: .confidenceScore)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.LanguageInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
