// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Tools
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleGax
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// The response message for
  /// [Tools.ListToolVersions][google.cloud.dialogflow.cx.v3.Tools.ListToolVersions].
  ///
  /// [google.cloud.dialogflow.cx.v3.Tools.ListToolVersions]: <doc:ToolsClient/listToolVersions(request:options:)>
  public struct ListToolVersionsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
    GoogleGax._PaginatedResponse,
    Sendable
  {
    /// The list of tool versions. There will be a maximum number of items
    /// returned based on the page_size field in the request.
    public var toolVersions: [ToolVersion] = []

    /// Token to retrieve the next page of results, or empty if there are no more
    /// results in the list.
    public var nextPageToken: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ListToolVersionsResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListToolVersionsResponse().with { $0.toolVersions = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let toolVersions = CodingKeys(stringValue: "toolVersions")
      static let nextPageToken = CodingKeys(stringValue: "nextPageToken")

      static let _knownKeys: Set<Swift.String> = [
        "toolVersions",
        "nextPageToken",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([ToolVersion].self, forKey: .toolVersions) {
        self.toolVersions = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
        self.nextPageToken = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.toolVersions, forKey: .toolVersions)
      try container.encode(self.nextPageToken, forKey: .nextPageToken)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.ListToolVersionsResponse"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }

    public func _getPaginatedItems() -> [ToolVersion] {
      return self.toolVersions
    }

    public func _nextPageToken() -> Swift.String {
      return self.nextPageToken
    }
  }
#endif
