// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Deployments
  import Foundation
  import GoogleCloudWkt

  /// The request message for
  /// [Deployments.ListDeployments][google.cloud.dialogflow.cx.v3.Deployments.ListDeployments].
  ///
  /// [google.cloud.dialogflow.cx.v3.Deployments.ListDeployments]: <doc:Deployments/listDeployments(request:)>
  public struct ListDeploymentsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The [Environment][google.cloud.dialogflow.cx.v3.Environment] to
    /// list all environments for. Format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/environments/<EnvironmentID>`.
    ///
    /// [google.cloud.dialogflow.cx.v3.Environment]: <doc:Environment>
    public var parent: Swift.String = Swift.String()

    /// The maximum number of items to return in a single page. By default 20 and
    /// at most 100.
    public var pageSize: Swift.Int32 = Swift.Int32()

    /// The next_page_token value returned from a previous list request.
    public var pageToken: Swift.String = Swift.String()

    /// Initialize a new instance of `ListDeploymentsRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListDeploymentsRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.ListDeploymentsRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
