// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Sessions
  import Foundation
  import GoogleCloudWkt

  /// Response of [MatchIntent][].
  public struct MatchIntentResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Match results, if more than one, ordered descendingly by the confidence
    /// we have that the particular intent matches the query.
    public var matches: [Match] = []

    /// The current [Page][google.cloud.dialogflow.cx.v3.Page]. Some, not all
    /// fields are filled in this message, including but not limited to `name` and
    /// `display_name`.
    ///
    /// [google.cloud.dialogflow.cx.v3.Page]: <doc:Page>
    public var currentPage: Page? = nil

    /// The original conversational query.
    public var query: OneOf_Query? = nil

    /// Initialize a new instance of `MatchIntentResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MatchIntentResponse().with { $0.text = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case text = "text"
      case triggerIntent = "triggerIntent"
      case transcript = "transcript"
      case triggerEvent = "triggerEvent"
      case matches = "matches"
      case currentPage = "currentPage"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.matches = try container.decode([Match].self, forKey: .matches)
      self.currentPage = try container.decodeIfPresent(Page.self, forKey: .currentPage)

      var query: OneOf_Query? = nil
      let queryCheckAndSet = {
        if query != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'query'"))
        }
        query = $0
      }
      if let text = try container.decodeIfPresent(Swift.String.self, forKey: .text) {
        try queryCheckAndSet(.text(text))
      }
      if let triggerIntent = try container.decodeIfPresent(
        Swift.String.self, forKey: .triggerIntent)
      {
        try queryCheckAndSet(.triggerIntent(triggerIntent))
      }
      if let transcript = try container.decodeIfPresent(Swift.String.self, forKey: .transcript) {
        try queryCheckAndSet(.transcript(transcript))
      }
      if let triggerEvent = try container.decodeIfPresent(Swift.String.self, forKey: .triggerEvent)
      {
        try queryCheckAndSet(.triggerEvent(triggerEvent))
      }
      self.query = query
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.matches, forKey: .matches)
      try container.encode(self.currentPage, forKey: .currentPage)

      if let choice = self.query {
        switch choice {
        case .text(let value):
          try container.encode(value, forKey: .text)
        case .triggerIntent(let value):
          try container.encode(value, forKey: .triggerIntent)
        case .transcript(let value):
          try container.encode(value, forKey: .transcript)
        case .triggerEvent(let value):
          try container.encode(value, forKey: .triggerEvent)
        }
      }
    }

    /// The original conversational query.
    public enum OneOf_Query: Codable, Equatable, Sendable {
      /// If [natural language text][google.cloud.dialogflow.cx.v3.TextInput] was
      /// provided as input, this field will contain a copy of the text.
      ///
      /// [google.cloud.dialogflow.cx.v3.TextInput]: <doc:TextInput>
      case text(Swift.String)
      /// If an [intent][google.cloud.dialogflow.cx.v3.IntentInput] was provided as
      /// input, this field will contain a copy of the intent identifier. Format:
      /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/intents/<IntentID>`.
      ///
      /// [google.cloud.dialogflow.cx.v3.IntentInput]: <doc:IntentInput>
      case triggerIntent(Swift.String)
      /// If [natural language speech
      /// audio][google.cloud.dialogflow.cx.v3.AudioInput] was provided as input,
      /// this field will contain the transcript for the audio.
      ///
      /// [google.cloud.dialogflow.cx.v3.AudioInput]: <doc:AudioInput>
      case transcript(Swift.String)
      /// If an [event][google.cloud.dialogflow.cx.v3.EventInput] was provided as
      /// input, this field will contain a copy of the event name.
      ///
      /// [google.cloud.dialogflow.cx.v3.EventInput]: <doc:EventInput>
      case triggerEvent(Swift.String)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.MatchIntentResponse"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
