// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Agents && Changelogs && Deployments && EntityTypes && Environments && Examples && Experiments && Flows && Generators && Intents && Pages && Playbooks && SecuritySettingsService && SessionEntityTypes && Sessions && TestCases && Tools && TransitionRouteGroups && Versions && Webhooks
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Represents page information communicated to and from the webhook.
  public struct PageInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Always present for
    /// [WebhookRequest][google.cloud.dialogflow.cx.v3.WebhookRequest]. Ignored for
    /// [WebhookResponse][google.cloud.dialogflow.cx.v3.WebhookResponse]. The
    /// unique identifier of the current page. Format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/flows/<FlowID>/pages/<PageID>`.
    ///
    /// [google.cloud.dialogflow.cx.v3.WebhookRequest]: <doc:WebhookRequest>
    /// [google.cloud.dialogflow.cx.v3.WebhookResponse]: <doc:WebhookResponse>
    public var currentPage: Swift.String = Swift.String()

    /// Always present for
    /// [WebhookRequest][google.cloud.dialogflow.cx.v3.WebhookRequest]. Ignored for
    /// [WebhookResponse][google.cloud.dialogflow.cx.v3.WebhookResponse]. The
    /// display name of the current page.
    ///
    /// [google.cloud.dialogflow.cx.v3.WebhookRequest]: <doc:WebhookRequest>
    /// [google.cloud.dialogflow.cx.v3.WebhookResponse]: <doc:WebhookResponse>
    public var displayName: Swift.String = Swift.String()

    /// Optional for both
    /// [WebhookRequest][google.cloud.dialogflow.cx.v3.WebhookRequest] and
    /// [WebhookResponse][google.cloud.dialogflow.cx.v3.WebhookResponse].
    /// Information about the form.
    ///
    /// [google.cloud.dialogflow.cx.v3.WebhookRequest]: <doc:WebhookRequest>
    /// [google.cloud.dialogflow.cx.v3.WebhookResponse]: <doc:WebhookResponse>
    public var formInfo: PageInfo.FormInfo? = nil

    /// Initialize a new instance of `PageInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = PageInfo().with { $0.currentPage = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Represents form information.
    public struct FormInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Optional for both
      /// [WebhookRequest][google.cloud.dialogflow.cx.v3.WebhookRequest] and
      /// [WebhookResponse][google.cloud.dialogflow.cx.v3.WebhookResponse]. The
      /// parameters contained in the form. Note that the webhook cannot add or
      /// remove any form parameter.
      ///
      /// [google.cloud.dialogflow.cx.v3.WebhookRequest]: <doc:WebhookRequest>
      /// [google.cloud.dialogflow.cx.v3.WebhookResponse]: <doc:WebhookResponse>
      public var parameterInfo: [PageInfo.FormInfo.ParameterInfo] = []

      /// Initialize a new instance of `FormInfo`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = FormInfo().with { $0.parameterInfo = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      /// Represents parameter information.
      public struct ParameterInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
        Sendable
      {
        /// Always present for
        /// [WebhookRequest][google.cloud.dialogflow.cx.v3.WebhookRequest].
        /// Required for
        /// [WebhookResponse][google.cloud.dialogflow.cx.v3.WebhookResponse].
        /// The human-readable name of the parameter, unique within the form. This
        /// field cannot be modified by the webhook.
        ///
        /// [google.cloud.dialogflow.cx.v3.WebhookRequest]: <doc:WebhookRequest>
        /// [google.cloud.dialogflow.cx.v3.WebhookResponse]: <doc:WebhookResponse>
        public var displayName: Swift.String = Swift.String()

        /// Optional for both
        /// [WebhookRequest][google.cloud.dialogflow.cx.v3.WebhookRequest] and
        /// [WebhookResponse][google.cloud.dialogflow.cx.v3.WebhookResponse].
        /// Indicates whether the parameter is required. Optional parameters will
        /// not trigger prompts; however, they are filled if the user specifies
        /// them. Required parameters must be filled before form filling concludes.
        ///
        /// [google.cloud.dialogflow.cx.v3.WebhookRequest]: <doc:WebhookRequest>
        /// [google.cloud.dialogflow.cx.v3.WebhookResponse]: <doc:WebhookResponse>
        public var `required`: Swift.Bool = Swift.Bool()

        /// Always present for
        /// [WebhookRequest][google.cloud.dialogflow.cx.v3.WebhookRequest].
        /// Required for
        /// [WebhookResponse][google.cloud.dialogflow.cx.v3.WebhookResponse]. The
        /// state of the parameter. This field can be set to
        /// [INVALID][google.cloud.dialogflow.cx.v3.PageInfo.FormInfo.ParameterInfo.ParameterState.INVALID]
        /// by the webhook to invalidate the parameter; other values set by the
        /// webhook will be ignored.
        ///
        /// [google.cloud.dialogflow.cx.v3.PageInfo.FormInfo.ParameterInfo.ParameterState.INVALID]: <doc:PageInfo/FormInfo/ParameterInfo/ParameterState/invalid>
        /// [google.cloud.dialogflow.cx.v3.WebhookRequest]: <doc:WebhookRequest>
        /// [google.cloud.dialogflow.cx.v3.WebhookResponse]: <doc:WebhookResponse>
        public var state: PageInfo.FormInfo.ParameterInfo.ParameterState = PageInfo.FormInfo
          .ParameterInfo.ParameterState()

        /// Optional for both
        /// [WebhookRequest][google.cloud.dialogflow.cx.v3.WebhookRequest] and
        /// [WebhookResponse][google.cloud.dialogflow.cx.v3.WebhookResponse]. The
        /// value of the parameter. This field can be set by the webhook to change
        /// the parameter value.
        ///
        /// [google.cloud.dialogflow.cx.v3.WebhookRequest]: <doc:WebhookRequest>
        /// [google.cloud.dialogflow.cx.v3.WebhookResponse]: <doc:WebhookResponse>
        public var value: GoogleCloudWkt.Value? = nil

        /// Optional for
        /// [WebhookRequest][google.cloud.dialogflow.cx.v3.WebhookRequest]. Ignored
        /// for [WebhookResponse][google.cloud.dialogflow.cx.v3.WebhookResponse].
        /// Indicates if the parameter value was just collected on the last
        /// conversation turn.
        ///
        /// [google.cloud.dialogflow.cx.v3.WebhookRequest]: <doc:WebhookRequest>
        /// [google.cloud.dialogflow.cx.v3.WebhookResponse]: <doc:WebhookResponse>
        public var justCollected: Swift.Bool = Swift.Bool()

        /// Initialize a new instance of `ParameterInfo`.
        public init() {}

        /// Use `config` to return a new instance of this object, with some fields updated.
        ///
        /// Commonly used to initialize the value, for example:
        ///
        /// ```
        /// let value = ParameterInfo().with { $0.displayName = ... }
        /// ```
        public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
          var copy = self
          try config(&copy)
          return copy
        }

        private enum CodingKeys: Swift.String, CodingKey {
          case displayName = "displayName"
          case `required` = "required"
          case state = "state"
          case value = "value"
          case justCollected = "justCollected"
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: CodingKeys.self)
          self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
          self.`required` = try container.decode(Swift.Bool.self, forKey: .`required`)
          self.state = try container.decode(
            PageInfo.FormInfo.ParameterInfo.ParameterState.self, forKey: .state)
          self.value = try container.decodeIfPresent(GoogleCloudWkt.Value.self, forKey: .value)
          self.justCollected = try container.decode(Swift.Bool.self, forKey: .justCollected)
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: CodingKeys.self)
          try container.encode(self.displayName, forKey: .displayName)
          try container.encode(self.`required`, forKey: .`required`)
          try container.encode(self.state, forKey: .state)
          try container.encode(self.value, forKey: .value)
          try container.encode(self.justCollected, forKey: .justCollected)
        }

        /// Represents the state of a parameter.
        public enum ParameterState: Codable, Equatable, Sendable {
          /// Not specified. This value should be never used.
          case unspecified
          /// Indicates that the parameter does not have a value.
          case empty
          /// Indicates that the parameter value is invalid. This field can be used
          /// by the webhook to invalidate the parameter and ask the server to
          /// collect it from the user again.
          case invalid
          /// Indicates that the parameter has a value.
          case filled
          /// Encodes an unknown integer value.
          ///
          /// The most common cause for an unknown values is for the service to send
          /// a value unknown to the library. We recommend you update your library to
          /// the latest version.
          case unknownIntValue(Int)
          /// Encodes an unknown string value.
          ///
          /// The most common cause for an unknown values is for the service to send
          /// a value unknown to the library. We recommend you update your library to
          /// the latest version.
          case unknownStringValue(String)

          public init() {
            self = .unspecified
          }

          /// Returns the integer value associated with the enumeration.
          ///
          /// If the enumeration was initialized with an unknown string value, this returns `nil`.
          public var intValue: Int? {
            switch self {
            case .unspecified: return 0
            case .empty: return 1
            case .invalid: return 2
            case .filled: return 3
            case .unknownIntValue(let v): return v
            case .unknownStringValue: return nil
            }
          }

          /// Returns the string value (or name) associated with the enumeration.
          ///
          /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
          public var stringValue: Swift.String? {
            switch self {
            case .unspecified: return "PARAMETER_STATE_UNSPECIFIED"
            case .empty: return "EMPTY"
            case .invalid: return "INVALID"
            case .filled: return "FILLED"
            case .unknownIntValue: return nil
            case .unknownStringValue(let v): return v
            }
          }

          /// Initialize from a string value.
          ///
          /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ParameterState/unknownStringValue(_:)).
          public init(stringValue: Swift.String) {
            switch stringValue {
            case "PARAMETER_STATE_UNSPECIFIED": self = .unspecified
            case "EMPTY": self = .empty
            case "INVALID": self = .invalid
            case "FILLED": self = .filled
            default: self = .unknownStringValue(stringValue)
            }
          }

          /// Initialize from an integer value.
          ///
          /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ParameterState/unknownIntValue(_:)).
          public init(intValue: Int) {
            switch intValue {
            case 0: self = .unspecified
            case 1: self = .empty
            case 2: self = .invalid
            case 3: self = .filled
            default: self = .unknownIntValue(intValue)
            }
          }

          public init(from decoder: Decoder) throws {
            let container = try decoder.singleValueContainer()
            if let v = try? container.decode(Int.self) {
              self.init(intValue: v)
              return
            }
            if let s = try? container.decode(String.self) {
              if let v = Int(s) {
                self.init(intValue: v)
              } else {
                self.init(stringValue: s)
              }
              return
            }
            throw DecodingError.dataCorruptedError(
              in: container, debugDescription: "Expected enum value, must be integer or string.")
          }

          public func encode(to encoder: Encoder) throws {
            var container = encoder.singleValueContainer()
            switch self {
            case .unspecified: return try container.encode(0)
            case .empty: return try container.encode(1)
            case .invalid: return try container.encode(2)
            case .filled: return try container.encode(3)
            case .unknownIntValue(let v): return try container.encode(v)
            case .unknownStringValue(let v): return try container.encode(v)
            }
          }
        }

        public static var _anyTypeUrl: Swift.String {
          return "type.googleapis.com/google.cloud.dialogflow.cx.v3.PageInfo.FormInfo.ParameterInfo"
        }
        public init(fromAny any: GoogleCloudWkt.`Any`) throws {
          self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
        }
        public func _pack() throws -> GoogleCloudWkt.Struct {
          return try GoogleCloudWkt._slowAnySerialize(message: self)
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.dialogflow.cx.v3.PageInfo.FormInfo"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.PageInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
