// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Flows || Playbooks || Sessions || TestCases
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Defines the properties of a parameter.
  /// Used to define parameters used in the agent and the
  /// input / output parameters for each fulfillment.
  public struct ParameterDefinition: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Name of parameter.
    public var name: Swift.String = Swift.String()

    /// Type of parameter.
    @available(*, deprecated)
    public var type: ParameterDefinition.ParameterType = ParameterDefinition.ParameterType()

    /// Optional. Type schema of parameter.
    public var typeSchema: TypeSchema? = nil

    /// Human-readable description of the parameter. Limited to 300 characters.
    public var description: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ParameterDefinition`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ParameterDefinition().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let type = CodingKeys(stringValue: "type")
      static let typeSchema = CodingKeys(stringValue: "typeSchema")
      static let description = CodingKeys(stringValue: "description")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "type",
        "typeSchema",
        "description",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(
        ParameterDefinition.ParameterType.self, forKey: .type)
      {
        self.type = value
      }
      self.typeSchema = try container.decodeIfPresent(TypeSchema.self, forKey: .typeSchema)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.type, forKey: .type)
      try container.encodeIfPresent(self.typeSchema, forKey: .typeSchema)
      try container.encode(self.description, forKey: .description)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Parameter types are used for validation.
    /// These types are consistent with
    /// [google.protobuf.Value][google.protobuf.Value].
    ///
    /// [google.protobuf.Value]: https://www.google.com/search?q=Swift+google.protobuf+GoogleWKT.Value
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum ParameterType: Codable, Equatable, Sendable {
      /// Not specified. No validation will be performed.
      case unspecified
      /// Represents any string value.
      case string
      /// Represents any number value.
      case number
      /// Represents a boolean value.
      case boolean
      /// Represents a null value.
      case null
      /// Represents any object value.
      case object
      /// Represents a repeated value.
      case list
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .string: return 1
        case .number: return 2
        case .boolean: return 3
        case .null: return 4
        case .object: return 5
        case .list: return 6
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "PARAMETER_TYPE_UNSPECIFIED"
        case .string: return "STRING"
        case .number: return "NUMBER"
        case .boolean: return "BOOLEAN"
        case .null: return "NULL"
        case .object: return "OBJECT"
        case .list: return "LIST"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ParameterType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "PARAMETER_TYPE_UNSPECIFIED": self = .unspecified
        case "STRING": self = .string
        case "NUMBER": self = .number
        case "BOOLEAN": self = .boolean
        case "NULL": self = .null
        case "OBJECT": self = .object
        case "LIST": self = .list
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ParameterType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .string
        case 2: self = .number
        case 3: self = .boolean
        case 4: self = .null
        case 5: self = .object
        case 6: self = .list
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("PARAMETER_TYPE_UNSPECIFIED")
        case .string: return try container.encode("STRING")
        case .number: return try container.encode("NUMBER")
        case .boolean: return try container.encode("BOOLEAN")
        case .null: return try container.encode("NULL")
        case .object: return try container.encode("OBJECT")
        case .list: return try container.encode("LIST")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.ParameterDefinition"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
