// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Sessions || TestCases
  import Foundation
  import GoogleCloudWkt

  /// Represents the query input. It can contain one of:
  ///
  /// 1. A conversational query in the form of text.
  ///
  /// 2. An intent query that specifies which intent to trigger.
  ///
  /// 3. Natural language speech audio to be processed.
  ///
  /// 4. An event to be triggered.
  ///
  /// 5. DTMF digits to invoke an intent and fill in parameter value.
  ///
  /// 6. The results of a tool executed by the client.
  public struct QueryInput: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The language of the input. See [Language
    /// Support](https://cloud.google.com/dialogflow/cx/docs/reference/language)
    /// for a list of the currently supported language codes. Note that queries in
    /// the same session do not necessarily need to specify the same language.
    public var languageCode: Swift.String = Swift.String()

    /// Required. The input specification.
    public var input: OneOf_Input? = nil

    /// Initialize a new instance of `QueryInput`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QueryInput().with { $0.text = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case text = "text"
      case intent = "intent"
      case audio = "audio"
      case event = "event"
      case dtmf = "dtmf"
      case toolCallResult = "toolCallResult"
      case languageCode = "languageCode"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.languageCode = try container.decode(Swift.String.self, forKey: .languageCode)

      var input: OneOf_Input? = nil
      let inputCheckAndSet = {
        if input != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'input'"))
        }
        input = $0
      }
      if let text = try container.decodeIfPresent(TextInput?.self, forKey: .text) {
        try inputCheckAndSet(.text(text))
      }
      if let intent = try container.decodeIfPresent(IntentInput?.self, forKey: .intent) {
        try inputCheckAndSet(.intent(intent))
      }
      if let audio = try container.decodeIfPresent(AudioInput?.self, forKey: .audio) {
        try inputCheckAndSet(.audio(audio))
      }
      if let event = try container.decodeIfPresent(EventInput?.self, forKey: .event) {
        try inputCheckAndSet(.event(event))
      }
      if let dtmf = try container.decodeIfPresent(DtmfInput?.self, forKey: .dtmf) {
        try inputCheckAndSet(.dtmf(dtmf))
      }
      if let toolCallResult = try container.decodeIfPresent(
        ToolCallResult?.self, forKey: .toolCallResult)
      {
        try inputCheckAndSet(.toolCallResult(toolCallResult))
      }
      self.input = input
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.languageCode, forKey: .languageCode)

      if let choice = self.input {
        switch choice {
        case .text(let value):
          try container.encode(value, forKey: .text)
        case .intent(let value):
          try container.encode(value, forKey: .intent)
        case .audio(let value):
          try container.encode(value, forKey: .audio)
        case .event(let value):
          try container.encode(value, forKey: .event)
        case .dtmf(let value):
          try container.encode(value, forKey: .dtmf)
        case .toolCallResult(let value):
          try container.encode(value, forKey: .toolCallResult)
        }
      }
    }

    /// Required. The input specification.
    public enum OneOf_Input: Codable, Equatable, Sendable {
      /// The natural language text to be processed.
      indirect case text(TextInput?)
      /// The intent to be triggered.
      indirect case intent(IntentInput?)
      /// The natural language speech audio to be processed.
      indirect case audio(AudioInput?)
      /// The event to be triggered.
      indirect case event(EventInput?)
      /// The DTMF event to be handled.
      indirect case dtmf(DtmfInput?)
      /// The results of a tool executed by the client.
      indirect case toolCallResult(ToolCallResult?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.QueryInput"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
