// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SecuritySettingsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleCloudLocation
  @_spi(GoogleCloudInternal) public import GoogleLongRunning
  @_spi(GoogleCloudInternal) public import GoogleWKT
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// Service for managing security settings for Dialogflow.
  ///
  /// @Snippet(path: "SecuritySettingsServiceQuickstart")
  public final class SecuritySettingsServiceClient: Clients.SecuritySettingsServiceProtocol,
    Sendable
  {
    let inner: any Clients.SecuritySettingsServiceStub

    /// Creates a new `SecuritySettingsServiceClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.SecuritySettingsServiceStub =
        try Clients.SecuritySettingsServiceTransport(options)
      inner = Clients.SecuritySettingsServiceRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.SecuritySettingsServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Create security settings in the specified location.
    ///
    /// @Snippet(path: "SecuritySettingsService_CreateSecuritySettings")
    public func createSecuritySettings(
      request: CreateSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings {
      try await self.inner.createSecuritySettings(request: request, options: options)
    }

    /// Retrieves the specified
    /// [SecuritySettings][google.cloud.dialogflow.cx.v3.SecuritySettings]. The
    /// returned settings may be stale by up to 1 minute.
    ///
    /// [google.cloud.dialogflow.cx.v3.SecuritySettings]: <doc:SecuritySettings>
    ///
    /// @Snippet(path: "SecuritySettingsService_GetSecuritySettings")
    public func getSecuritySettings(
      request: GetSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings {
      try await self.inner.getSecuritySettings(request: request, options: options)
    }

    /// Updates the specified
    /// [SecuritySettings][google.cloud.dialogflow.cx.v3.SecuritySettings].
    ///
    /// [google.cloud.dialogflow.cx.v3.SecuritySettings]: <doc:SecuritySettings>
    ///
    /// @Snippet(path: "SecuritySettingsService_UpdateSecuritySettings")
    public func updateSecuritySettings(
      request: UpdateSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings {
      try await self.inner.updateSecuritySettings(request: request, options: options)
    }

    /// Returns the list of all security settings in the specified location.
    ///
    /// @Snippet(path: "SecuritySettingsService_ListSecuritySettings")
    public func listSecuritySettings(
      request: ListSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.ListSecuritySettingsResponse {
      try await self.inner.listSecuritySettings(request: request, options: options)
    }

    /// Deletes the specified
    /// [SecuritySettings][google.cloud.dialogflow.cx.v3.SecuritySettings].
    ///
    /// [google.cloud.dialogflow.cx.v3.SecuritySettings]: <doc:SecuritySettings>
    ///
    /// @Snippet(path: "SecuritySettingsService_DeleteSecuritySettings")
    public func deleteSecuritySettings(
      request: DeleteSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.deleteSecuritySettings(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "SecuritySettingsService_ListLocations")
    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Gets information about a location.
    ///
    /// @Snippet(path: "SecuritySettingsService_GetLocation")
    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "SecuritySettingsService_ListOperations")
    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "SecuritySettingsService_GetOperation")
    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "SecuritySettingsService_CancelOperation")
    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `SecuritySettingsServiceClient`.
    ///
    /// To mock `SecuritySettingsServiceClient` change your functions to receive
    /// `some SecuritySettingsServiceProtocol` or `any SecuritySettingsServiceProtocol`
    /// and pass a mock implementation in your tests.
    public protocol SecuritySettingsServiceProtocol: Sendable {
      /// See `SecuritySettingsServiceClient.createSecuritySettings`.
      func createSecuritySettings(
        request: CreateSecuritySettingsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings

      /// See `SecuritySettingsServiceClient.getSecuritySettings`.
      func getSecuritySettings(
        request: GetSecuritySettingsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings

      /// See `SecuritySettingsServiceClient.updateSecuritySettings`.
      func updateSecuritySettings(
        request: UpdateSecuritySettingsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings

      /// See `SecuritySettingsServiceClient.listSecuritySettings`.
      func listSecuritySettings(
        request: ListSecuritySettingsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.ListSecuritySettingsResponse

      /// See `SecuritySettingsServiceClient.deleteSecuritySettings`.
      func deleteSecuritySettings(
        request: DeleteSecuritySettingsRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `SecuritySettingsServiceClient.listLocations`.
      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      /// See `SecuritySettingsServiceClient.getLocation`.
      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      /// See `SecuritySettingsServiceClient.listOperations`.
      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      /// See `SecuritySettingsServiceClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws
    }
  }

  // Default implementations
  extension Clients.SecuritySettingsServiceProtocol {
    public func createSecuritySettings(request: CreateSecuritySettingsRequest) async throws
      -> GoogleCloudDialogflowCXV3.SecuritySettings
    {
      try await self.createSecuritySettings(request: request, options: .init())
    }

    public func createSecuritySettings(
      request: CreateSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createSecuritySettings(
      parent: Swift.String,
      securitySettings: SecuritySettings?,
    ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings {
      let request = CreateSecuritySettingsRequest().with {
        $0.parent = parent
        $0.securitySettings = securitySettings
      }
      return try await self.createSecuritySettings(request: request)
    }

    public func getSecuritySettings(request: GetSecuritySettingsRequest) async throws
      -> GoogleCloudDialogflowCXV3.SecuritySettings
    {
      try await self.getSecuritySettings(request: request, options: .init())
    }

    public func getSecuritySettings(
      request: GetSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getSecuritySettings(
      name: Swift.String,
    ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings {
      let request = GetSecuritySettingsRequest().with {
        $0.name = name
      }
      return try await self.getSecuritySettings(request: request)
    }

    public func updateSecuritySettings(request: UpdateSecuritySettingsRequest) async throws
      -> GoogleCloudDialogflowCXV3.SecuritySettings
    {
      try await self.updateSecuritySettings(request: request, options: .init())
    }

    public func updateSecuritySettings(
      request: UpdateSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings {
      throw GoogleGax.RequestError.unimplemented
    }

    public func updateSecuritySettings(
      securitySettings: SecuritySettings?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> GoogleCloudDialogflowCXV3.SecuritySettings {
      let request = UpdateSecuritySettingsRequest().with {
        $0.securitySettings = securitySettings
        $0.updateMask = updateMask
      }
      return try await self.updateSecuritySettings(request: request)
    }

    public func listSecuritySettings(request: ListSecuritySettingsRequest) async throws
      -> GoogleCloudDialogflowCXV3.ListSecuritySettingsResponse
    {
      try await self.listSecuritySettings(request: request, options: .init())
    }

    public func listSecuritySettings(
      request: ListSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.ListSecuritySettingsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listSecuritySettings(
      byItem: ListSecuritySettingsRequest
    ) -> any AsyncSequence<SecuritySettings, Swift.Error> {
      self.listSecuritySettings(byItem: byItem, options: .init())
    }

    /// Returns the list of all security settings in the specified location.
    ///
    /// @Snippet(path: "SecuritySettingsService_ListSecuritySettings")
    public func listSecuritySettings(
      byItem: ListSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<SecuritySettings, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDialogflowCXV3.ListSecuritySettingsResponse
        in
        var request = byItem
        request.pageToken = token
        return try await self.listSecuritySettings(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listSecuritySettings(
      parent: Swift.String,
    ) -> any AsyncSequence<SecuritySettings, Swift.Error> {
      let request = ListSecuritySettingsRequest().with {
        $0.parent = parent
      }
      return self.listSecuritySettings(byItem: request)
    }

    public func deleteSecuritySettings(request: DeleteSecuritySettingsRequest) async throws {
      try await self.deleteSecuritySettings(request: request, options: .init())
    }

    public func deleteSecuritySettings(
      request: DeleteSecuritySettingsRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteSecuritySettings(
      name: Swift.String,
    ) async throws {
      let request = DeleteSecuritySettingsRequest().with {
        $0.name = name
      }
      try await self.deleteSecuritySettings(request: request)
    }

    public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse
    {
      try await self.listLocations(request: request, options: .init())
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      self.listLocations(byItem: byItem, options: .init())
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "SecuritySettingsService_ListLocations")
    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location
    {
      try await self.getLocation(request: request, options: .init())
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      self.listOperations(byItem: byItem, options: .init())
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "SecuritySettingsService_ListOperations")
    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let request = GoogleLongRunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return self.listOperations(byItem: request)
    }

    public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongRunning.Operation {
      let request = GoogleLongRunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable,
    message: "Enable the 'SecuritySettingsService' trait in Package.swift to use this client."
  )
  public final class SecuritySettingsServiceClient: Sendable {
    @available(
      *, unavailable,
      message: "Enable the 'SecuritySettingsService' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
