// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if SecuritySettingsService
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleCloudWkt
  import GoogleLongRunning
  import GoogleCloudGax

  extension Clients {
    final class SecuritySettingsServiceRetry: SecuritySettingsServiceStub {
      let inner: any SecuritySettingsServiceStub
      let options: GoogleCloudGax.ClientOptions

      public init(_ inner: any SecuritySettingsServiceStub, options: GoogleCloudGax.ClientOptions) {
        self.inner = inner
        self.options = options
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        idempotent: Swift.Bool,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        let loop = GoogleCloudGax._RetryLoop(
          options: options, withDefault: self.options, idempotent: idempotent,
        )
        let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
          var attemptOptions = options
          attemptOptions.attemptTimeout = attemptTimeout
          return try await action(request, attemptOptions)
        }
        return try await loop.run(attempt: attempt)
      }

      public func createSecuritySettings(
        request: CreateSecuritySettingsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCxV3.SecuritySettings {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: CreateSecuritySettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowCxV3.SecuritySettings
            in
            return try await self.inner.createSecuritySettings(request: r, options: o)
          })
      }

      public func getSecuritySettings(
        request: GetSecuritySettingsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCxV3.SecuritySettings {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GetSecuritySettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowCxV3.SecuritySettings
            in
            return try await self.inner.getSecuritySettings(request: r, options: o)
          })
      }

      public func updateSecuritySettings(
        request: UpdateSecuritySettingsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCxV3.SecuritySettings {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: UpdateSecuritySettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowCxV3.SecuritySettings
            in
            return try await self.inner.updateSecuritySettings(request: r, options: o)
          })
      }

      public func listSecuritySettings(
        request: ListSecuritySettingsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCxV3.ListSecuritySettingsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: ListSecuritySettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowCxV3.ListSecuritySettingsResponse
            in
            return try await self.inner.listSecuritySettings(request: r, options: o)
          })
      }

      public func deleteSecuritySettings(
        request: DeleteSecuritySettingsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: DeleteSecuritySettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> Void in
            return try await self.inner.deleteSecuritySettings(request: r, options: o)
          })
      }

      public func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudLocation.ListLocationsResponse
            in
            return try await self.inner.listLocations(request: r, options: o)
          })
      }

      public func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudLocation.Location
            in
            return try await self.inner.getLocation(request: r, options: o)
          })
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleLongRunning.ListOperationsResponse
            in
            return try await self.inner.listOperations(request: r, options: o)
          })
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: true,
          action: {
            (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleLongRunning.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          idempotent: false,
          action: {
            (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> Void in
            return try await self.inner.cancelOperation(request: r, options: o)
          })
      }
    }
  }
#endif
