// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Sessions
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// The result of sentiment analysis. Sentiment analysis inspects user input
  /// and identifies the prevailing subjective opinion, especially to determine a
  /// user's attitude as positive, negative, or neutral.
  public struct SentimentAnalysisResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Sentiment score between -1.0 (negative sentiment) and 1.0 (positive
    ///  sentiment).
    public var score: Swift.Float = Swift.Float()

    /// A non-negative number in the [0, +inf) range, which represents the absolute
    /// magnitude of sentiment, regardless of score (positive or negative).
    public var magnitude: Swift.Float = Swift.Float()

    /// Initialize a new instance of `SentimentAnalysisResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SentimentAnalysisResult().with { $0.score = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.SentimentAnalysisResult"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
