// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Sessions
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// The request to set the feedback for a bot answer.
  public struct SubmitAnswerFeedbackRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The name of the session the feedback was sent to.
    public var session: Swift.String = Swift.String()

    /// Required. ID of the response to update its feedback. This is the same as
    /// DetectIntentResponse.response_id.
    public var responseId: Swift.String = Swift.String()

    /// Required. Feedback provided for a bot answer.
    public var answerFeedback: AnswerFeedback? = nil

    /// Optional. The mask to control which fields to update. If the mask is not
    /// present, all fields will be updated.
    public var updateMask: GoogleCloudWkt.FieldMask? = nil

    /// Initialize a new instance of `SubmitAnswerFeedbackRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SubmitAnswerFeedbackRequest().with { $0.session = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.SubmitAnswerFeedbackRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
