// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TestCases
  import Foundation
  import GoogleCloudWkt

  /// Represents a test case.
  public struct TestCase: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The unique identifier of the test case.
    /// [TestCases.CreateTestCase][google.cloud.dialogflow.cx.v3.TestCases.CreateTestCase]
    /// will populate the name automatically. Otherwise use format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/testCases/<TestCaseID>`.
    ///
    /// [google.cloud.dialogflow.cx.v3.TestCases.CreateTestCase]: <doc:TestCases/createTestCase(request:)>
    public var name: Swift.String = Swift.String()

    /// Tags are short descriptions that users may apply to test cases for
    /// organizational and filtering purposes. Each tag should start with "#" and
    /// has a limit of 30 characters.
    public var tags: [Swift.String] = []

    /// Required. The human-readable name of the test case, unique within the
    /// agent. Limit of 200 characters.
    public var displayName: Swift.String = Swift.String()

    /// Additional freeform notes about the test case. Limit of 400 characters.
    public var notes: Swift.String = Swift.String()

    /// Config for the test case.
    public var testConfig: TestConfig? = nil

    /// The conversation turns uttered when the test case was created, in
    /// chronological order. These include the canonical set of agent utterances
    /// that should occur when the agent is working properly.
    public var testCaseConversationTurns: [ConversationTurn] = []

    /// Output only. When the test was created.
    public var creationTime: GoogleCloudWkt.Timestamp? = nil

    /// The latest test result.
    public var lastTestResult: TestCaseResult? = nil

    /// Initialize a new instance of `TestCase`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TestCase().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.TestCase"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
