// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TestCases
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Represents configurations for a test case.
  public struct TestConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Session parameters to be compared when calculating differences.
    public var trackingParameters: [Swift.String] = []

    /// Flow name to start the test case with.
    /// Format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/flows/<FlowID>`.
    ///
    ///  Only one of `flow` and `page` should be set to indicate the starting point
    ///  of the test case. If neither is set, the test case will start with start
    ///  page on the default start flow.
    public var flow: Swift.String = Swift.String()

    /// The [page][google.cloud.dialogflow.cx.v3.Page] to start the test case with.
    /// Format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/flows/<FlowID>/pages/<PageID>`.
    ///
    ///  Only one of `flow` and `page` should be set to indicate the starting point
    ///  of the test case. If neither is set, the test case will start with start
    ///  page on the default start flow.
    ///
    /// [google.cloud.dialogflow.cx.v3.Page]: <doc:Page>
    public var page: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TestConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TestConfig().with { $0.trackingParameters = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let trackingParameters = CodingKeys(stringValue: "trackingParameters")
      static let flow = CodingKeys(stringValue: "flow")
      static let page = CodingKeys(stringValue: "page")

      static let _knownKeys: Set<Swift.String> = [
        "trackingParameters",
        "flow",
        "page",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .trackingParameters)
      {
        self.trackingParameters = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .flow) {
        self.flow = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .page) {
        self.page = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.trackingParameters, forKey: .trackingParameters)
      try container.encode(self.flow, forKey: .flow)
      try container.encode(self.page, forKey: .page)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.TestConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
