// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TestCases || TransitionRouteGroups
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// A TransitionRouteGroup represents a group of
  /// [`TransitionRoutes`][google.cloud.dialogflow.cx.v3.TransitionRoute] to be
  /// used by a [Page][google.cloud.dialogflow.cx.v3.Page].
  ///
  /// [google.cloud.dialogflow.cx.v3.Page]: <doc:Page>
  /// [google.cloud.dialogflow.cx.v3.TransitionRoute]: <doc:TransitionRoute>
  public struct TransitionRouteGroup: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The unique identifier of the transition route group.
    /// [TransitionRouteGroups.CreateTransitionRouteGroup][google.cloud.dialogflow.cx.v3.TransitionRouteGroups.CreateTransitionRouteGroup]
    /// populates the name automatically. Format:
    /// `projects/<ProjectID>/locations/<LocationID>/agents/<AgentID>/flows/<FlowID>/transitionRouteGroups/<TransitionRouteGroupID>`
    /// .
    ///
    /// [google.cloud.dialogflow.cx.v3.TransitionRouteGroups.CreateTransitionRouteGroup]: <doc:TransitionRouteGroupsClient/createTransitionRouteGroup(request:options:)>
    public var name: Swift.String = Swift.String()

    /// Required. The human-readable name of the transition route group, unique
    /// within the flow. The display name can be no longer than 30 characters.
    public var displayName: Swift.String = Swift.String()

    /// Transition routes associated with the
    /// [TransitionRouteGroup][google.cloud.dialogflow.cx.v3.TransitionRouteGroup].
    ///
    /// [google.cloud.dialogflow.cx.v3.TransitionRouteGroup]: <doc:TransitionRouteGroup>
    public var transitionRoutes: [TransitionRoute] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TransitionRouteGroup`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TransitionRouteGroup().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let displayName = CodingKeys(stringValue: "displayName")
      static let transitionRoutes = CodingKeys(stringValue: "transitionRoutes")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "displayName",
        "transitionRoutes",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
        self.displayName = value
      }
      if let value = try container.decodeIfPresent(
        [TransitionRoute].self, forKey: .transitionRoutes)
      {
        self.transitionRoutes = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.displayName, forKey: .displayName)
      try container.encode(self.transitionRoutes, forKey: .transitionRoutes)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.cx.v3.TransitionRouteGroup"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
