// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if TransitionRouteGroups
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleCloudWkt
  import GoogleLongRunning
  import GoogleCloudGax

  /// Service for managing
  /// [TransitionRouteGroups][google.cloud.dialogflow.cx.v3.TransitionRouteGroup].
  ///
  /// [google.cloud.dialogflow.cx.v3.TransitionRouteGroup]: <doc:TransitionRouteGroup>
  ///
  /// @Snippet(path: "TransitionRouteGroupsQuickstart")
  public class TransitionRouteGroupsClient: Clients.TransitionRouteGroupsProtocol {
    let inner: any Clients.TransitionRouteGroupsStub

    /// Creates a new `TransitionRouteGroupsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any Clients.TransitionRouteGroupsStub = try Clients.TransitionRouteGroupsTransport(
        options)
      inner = Clients.TransitionRouteGroupsRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.TransitionRouteGroupsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Returns the list of all transition route groups in the specified flow.
    ///
    /// @Snippet(path: "TransitionRouteGroups_ListTransitionRouteGroups")
    public func listTransitionRouteGroups(
      request: ListTransitionRouteGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.ListTransitionRouteGroupsResponse {
      try await self.inner.listTransitionRouteGroups(request: request, options: options)
    }

    /// Returns the list of all transition route groups in the specified flow.
    ///
    /// @Snippet(path: "TransitionRouteGroups_ListTransitionRouteGroups")
    public func listTransitionRouteGroups(
      byItem: ListTransitionRouteGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TransitionRouteGroup, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws
          -> GoogleCloudDialogflowCXV3.ListTransitionRouteGroupsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listTransitionRouteGroups(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Retrieves the specified
    /// [TransitionRouteGroup][google.cloud.dialogflow.cx.v3.TransitionRouteGroup].
    ///
    /// [google.cloud.dialogflow.cx.v3.TransitionRouteGroup]: <doc:TransitionRouteGroup>
    ///
    /// @Snippet(path: "TransitionRouteGroups_GetTransitionRouteGroup")
    public func getTransitionRouteGroup(
      request: GetTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup {
      try await self.inner.getTransitionRouteGroup(request: request, options: options)
    }

    /// Creates an
    /// [TransitionRouteGroup][google.cloud.dialogflow.cx.v3.TransitionRouteGroup]
    /// in the specified flow.
    ///
    /// Note: You should always train a flow prior to sending it queries. See the
    /// [training
    /// documentation](https://cloud.google.com/dialogflow/cx/docs/concept/training).
    ///
    /// [google.cloud.dialogflow.cx.v3.TransitionRouteGroup]: <doc:TransitionRouteGroup>
    ///
    /// @Snippet(path: "TransitionRouteGroups_CreateTransitionRouteGroup")
    public func createTransitionRouteGroup(
      request: CreateTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup {
      try await self.inner.createTransitionRouteGroup(request: request, options: options)
    }

    /// Updates the specified
    /// [TransitionRouteGroup][google.cloud.dialogflow.cx.v3.TransitionRouteGroup].
    ///
    /// Note: You should always train a flow prior to sending it queries. See the
    /// [training
    /// documentation](https://cloud.google.com/dialogflow/cx/docs/concept/training).
    ///
    /// [google.cloud.dialogflow.cx.v3.TransitionRouteGroup]: <doc:TransitionRouteGroup>
    ///
    /// @Snippet(path: "TransitionRouteGroups_UpdateTransitionRouteGroup")
    public func updateTransitionRouteGroup(
      request: UpdateTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup {
      try await self.inner.updateTransitionRouteGroup(request: request, options: options)
    }

    /// Deletes the specified
    /// [TransitionRouteGroup][google.cloud.dialogflow.cx.v3.TransitionRouteGroup].
    ///
    /// Note: You should always train a flow prior to sending it queries. See the
    /// [training
    /// documentation](https://cloud.google.com/dialogflow/cx/docs/concept/training).
    ///
    /// [google.cloud.dialogflow.cx.v3.TransitionRouteGroup]: <doc:TransitionRouteGroup>
    ///
    /// @Snippet(path: "TransitionRouteGroups_DeleteTransitionRouteGroup")
    public func deleteTransitionRouteGroup(
      request: DeleteTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteTransitionRouteGroup(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "TransitionRouteGroups_ListLocations")
    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "TransitionRouteGroups_ListLocations")
    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Gets information about a location.
    ///
    /// @Snippet(path: "TransitionRouteGroups_GetLocation")
    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "TransitionRouteGroups_ListOperations")
    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "TransitionRouteGroups_ListOperations")
    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "TransitionRouteGroups_GetOperation")
    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "TransitionRouteGroups_CancelOperation")
    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `TransitionRouteGroupsClient`.
    ///
    /// To mock `TransitionRouteGroupsClient` change your functions to receive
    /// `some TransitionRouteGroupsProtocol` or `any TransitionRouteGroupsProtocol`
    /// and pass a mock implementation in your tests.
    public protocol TransitionRouteGroupsProtocol {
      /// See `TransitionRouteGroupsClient.listTransitionRouteGroups`.
      func listTransitionRouteGroups(request: ListTransitionRouteGroupsRequest) async throws
        -> GoogleCloudDialogflowCXV3.ListTransitionRouteGroupsResponse

      /// See `TransitionRouteGroupsClient.listTransitionRouteGroups`.
      func listTransitionRouteGroups(
        byItem: ListTransitionRouteGroupsRequest
      ) throws -> any AsyncSequence<TransitionRouteGroup, Swift.Error>

      /// See `TransitionRouteGroupsClient.listTransitionRouteGroups`.
      func listTransitionRouteGroups(
        parent: Swift.String,
      ) throws -> any AsyncSequence<TransitionRouteGroup, Swift.Error>

      /// See `TransitionRouteGroupsClient.getTransitionRouteGroup`.
      func getTransitionRouteGroup(request: GetTransitionRouteGroupRequest) async throws
        -> GoogleCloudDialogflowCXV3.TransitionRouteGroup

      /// See `TransitionRouteGroupsClient.getTransitionRouteGroup`.
      func getTransitionRouteGroup(
        name: Swift.String,
      ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup

      /// See `TransitionRouteGroupsClient.createTransitionRouteGroup`.
      func createTransitionRouteGroup(request: CreateTransitionRouteGroupRequest) async throws
        -> GoogleCloudDialogflowCXV3.TransitionRouteGroup

      /// See `TransitionRouteGroupsClient.createTransitionRouteGroup`.
      func createTransitionRouteGroup(
        parent: Swift.String,
        transitionRouteGroup: TransitionRouteGroup?,
      ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup

      /// See `TransitionRouteGroupsClient.updateTransitionRouteGroup`.
      func updateTransitionRouteGroup(request: UpdateTransitionRouteGroupRequest) async throws
        -> GoogleCloudDialogflowCXV3.TransitionRouteGroup

      /// See `TransitionRouteGroupsClient.updateTransitionRouteGroup`.
      func updateTransitionRouteGroup(
        transitionRouteGroup: TransitionRouteGroup?,
        updateMask: GoogleCloudWkt.FieldMask?,
      ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup

      /// See `TransitionRouteGroupsClient.deleteTransitionRouteGroup`.
      func deleteTransitionRouteGroup(request: DeleteTransitionRouteGroupRequest) async throws

      /// See `TransitionRouteGroupsClient.deleteTransitionRouteGroup`.
      func deleteTransitionRouteGroup(
        name: Swift.String,
      ) async throws

      /// See `TransitionRouteGroupsClient.listLocations`.
      func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
        -> GoogleCloudLocation.ListLocationsResponse

      /// See `TransitionRouteGroupsClient.listLocations`.
      func listLocations(
        byItem: GoogleCloudLocation.ListLocationsRequest
      ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

      /// See `TransitionRouteGroupsClient.getLocation`.
      func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
        -> GoogleCloudLocation.Location

      /// See `TransitionRouteGroupsClient.listOperations`.
      func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
        -> GoogleLongRunning.ListOperationsResponse

      /// See `TransitionRouteGroupsClient.listOperations`.
      func listOperations(
        byItem: GoogleLongRunning.ListOperationsRequest
      ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

      /// See `TransitionRouteGroupsClient.listOperations`.
      func listOperations(
        name: Swift.String,
        filter: Swift.String,
      ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

      /// See `TransitionRouteGroupsClient.cancelOperation`.
      func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

      /// See `TransitionRouteGroupsClient.cancelOperation`.
      func cancelOperation(
        name: Swift.String,
      ) async throws

      /// See `TransitionRouteGroupsClient.listTransitionRouteGroups`.
      func listTransitionRouteGroups(
        request: ListTransitionRouteGroupsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.ListTransitionRouteGroupsResponse

      /// See `TransitionRouteGroupsClient.listTransitionRouteGroups`.
      func listTransitionRouteGroups(
        byItem: ListTransitionRouteGroupsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<TransitionRouteGroup, Swift.Error>

      /// See `TransitionRouteGroupsClient.getTransitionRouteGroup`.
      func getTransitionRouteGroup(
        request: GetTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup

      /// See `TransitionRouteGroupsClient.createTransitionRouteGroup`.
      func createTransitionRouteGroup(
        request: CreateTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup

      /// See `TransitionRouteGroupsClient.updateTransitionRouteGroup`.
      func updateTransitionRouteGroup(
        request: UpdateTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup

      /// See `TransitionRouteGroupsClient.deleteTransitionRouteGroup`.
      func deleteTransitionRouteGroup(
        request: DeleteTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
      ) async throws

      /// See `TransitionRouteGroupsClient.listLocations`.
      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      /// See `TransitionRouteGroupsClient.listLocations`.
      func listLocations(
        byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

      /// See `TransitionRouteGroupsClient.getLocation`.
      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      /// See `TransitionRouteGroupsClient.listOperations`.
      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      /// See `TransitionRouteGroupsClient.listOperations`.
      func listOperations(
        byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

      /// See `TransitionRouteGroupsClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws
    }
  }

  // Default implementations
  extension Clients.TransitionRouteGroupsProtocol {
    public func listTransitionRouteGroups(request: ListTransitionRouteGroupsRequest) async throws
      -> GoogleCloudDialogflowCXV3.ListTransitionRouteGroupsResponse
    {
      try await self.listTransitionRouteGroups(request: request, options: .init())
    }

    public func listTransitionRouteGroups(
      request: ListTransitionRouteGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.ListTransitionRouteGroupsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listTransitionRouteGroups(
      byItem: ListTransitionRouteGroupsRequest
    ) throws -> any AsyncSequence<TransitionRouteGroup, Swift.Error> {
      try self.listTransitionRouteGroups(byItem: byItem, options: .init())
    }

    public func listTransitionRouteGroups(
      byItem: ListTransitionRouteGroupsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<TransitionRouteGroup, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws
          -> GoogleCloudDialogflowCXV3.ListTransitionRouteGroupsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listTransitionRouteGroups(
      parent: Swift.String,
    ) throws -> any AsyncSequence<TransitionRouteGroup, Swift.Error> {
      let request = ListTransitionRouteGroupsRequest().with {
        $0.parent = parent
      }
      return try self.listTransitionRouteGroups(byItem: request)
    }

    public func getTransitionRouteGroup(request: GetTransitionRouteGroupRequest) async throws
      -> GoogleCloudDialogflowCXV3.TransitionRouteGroup
    {
      try await self.getTransitionRouteGroup(request: request, options: .init())
    }

    public func getTransitionRouteGroup(
      request: GetTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getTransitionRouteGroup(
      name: Swift.String,
    ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup {
      let request = GetTransitionRouteGroupRequest().with {
        $0.name = name
      }
      return try await self.getTransitionRouteGroup(request: request)
    }

    public func createTransitionRouteGroup(request: CreateTransitionRouteGroupRequest) async throws
      -> GoogleCloudDialogflowCXV3.TransitionRouteGroup
    {
      try await self.createTransitionRouteGroup(request: request, options: .init())
    }

    public func createTransitionRouteGroup(
      request: CreateTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func createTransitionRouteGroup(
      parent: Swift.String,
      transitionRouteGroup: TransitionRouteGroup?,
    ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup {
      let request = CreateTransitionRouteGroupRequest().with {
        $0.parent = parent
        $0.transitionRouteGroup = transitionRouteGroup
      }
      return try await self.createTransitionRouteGroup(request: request)
    }

    public func updateTransitionRouteGroup(request: UpdateTransitionRouteGroupRequest) async throws
      -> GoogleCloudDialogflowCXV3.TransitionRouteGroup
    {
      try await self.updateTransitionRouteGroup(request: request, options: .init())
    }

    public func updateTransitionRouteGroup(
      request: UpdateTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func updateTransitionRouteGroup(
      transitionRouteGroup: TransitionRouteGroup?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudDialogflowCXV3.TransitionRouteGroup {
      let request = UpdateTransitionRouteGroupRequest().with {
        $0.transitionRouteGroup = transitionRouteGroup
        $0.updateMask = updateMask
      }
      return try await self.updateTransitionRouteGroup(request: request)
    }

    public func deleteTransitionRouteGroup(request: DeleteTransitionRouteGroupRequest) async throws
    {
      try await self.deleteTransitionRouteGroup(request: request, options: .init())
    }

    public func deleteTransitionRouteGroup(
      request: DeleteTransitionRouteGroupRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func deleteTransitionRouteGroup(
      name: Swift.String,
    ) async throws {
      let request = DeleteTransitionRouteGroupRequest().with {
        $0.name = name
      }
      try await self.deleteTransitionRouteGroup(request: request)
    }

    public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse
    {
      try await self.listLocations(request: request, options: .init())
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      try self.listLocations(byItem: byItem, options: .init())
    }

    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location
    {
      try await self.getLocation(request: request, options: .init())
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      try self.listOperations(byItem: byItem, options: .init())
    }

    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let request = GoogleLongRunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return try self.listOperations(byItem: request)
    }

    public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongRunning.Operation {
      let request = GoogleLongRunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }
  }
#endif
