// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Webhooks
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  @_spi(GoogleCloudInternal) public import GoogleCloudLocation
  @_spi(GoogleCloudInternal) public import GoogleLongRunning
  @_spi(GoogleCloudInternal) public import GoogleWKT
  @_spi(GoogleCloudInternal) public import GoogleGax

  /// Service for managing [Webhooks][google.cloud.dialogflow.cx.v3.Webhook].
  ///
  /// [google.cloud.dialogflow.cx.v3.Webhook]: <doc:Webhook>
  ///
  /// @Snippet(path: "WebhooksQuickstart")
  public final class WebhooksClient: Clients.WebhooksProtocol, Sendable {
    let inner: any Clients.WebhooksStub

    /// Creates a new `WebhooksClient` instance.
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {
      var inner: any Clients.WebhooksStub = try Clients.WebhooksTransport(options)
      inner = Clients.WebhooksRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.WebhooksLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Returns the list of all webhooks in the specified agent.
    ///
    /// @Snippet(path: "Webhooks_ListWebhooks")
    public func listWebhooks(
      request: ListWebhooksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.ListWebhooksResponse {
      try await self.inner.listWebhooks(request: request, options: options)
    }

    /// Retrieves the specified webhook.
    ///
    /// @Snippet(path: "Webhooks_GetWebhook")
    public func getWebhook(
      request: GetWebhookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Webhook {
      try await self.inner.getWebhook(request: request, options: options)
    }

    /// Creates a webhook in the specified agent.
    ///
    /// @Snippet(path: "Webhooks_CreateWebhook")
    public func createWebhook(
      request: CreateWebhookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Webhook {
      try await self.inner.createWebhook(request: request, options: options)
    }

    /// Updates the specified webhook.
    ///
    /// @Snippet(path: "Webhooks_UpdateWebhook")
    public func updateWebhook(
      request: UpdateWebhookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Webhook {
      try await self.inner.updateWebhook(request: request, options: options)
    }

    /// Deletes the specified webhook.
    ///
    /// @Snippet(path: "Webhooks_DeleteWebhook")
    public func deleteWebhook(
      request: DeleteWebhookRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.deleteWebhook(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "Webhooks_ListLocations")
    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Gets information about a location.
    ///
    /// @Snippet(path: "Webhooks_GetLocation")
    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Webhooks_ListOperations")
    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Webhooks_GetOperation")
    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Webhooks_CancelOperation")
    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `WebhooksClient`.
    ///
    /// To mock `WebhooksClient` change your functions to receive
    /// `some WebhooksProtocol` or `any WebhooksProtocol`
    /// and pass a mock implementation in your tests.
    public protocol WebhooksProtocol: Sendable {
      /// See `WebhooksClient.listWebhooks`.
      func listWebhooks(
        request: ListWebhooksRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.ListWebhooksResponse

      /// See `WebhooksClient.getWebhook`.
      func getWebhook(
        request: GetWebhookRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.Webhook

      /// See `WebhooksClient.createWebhook`.
      func createWebhook(
        request: CreateWebhookRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.Webhook

      /// See `WebhooksClient.updateWebhook`.
      func updateWebhook(
        request: UpdateWebhookRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowCXV3.Webhook

      /// See `WebhooksClient.deleteWebhook`.
      func deleteWebhook(
        request: DeleteWebhookRequest, options: GoogleGax.RequestOptions
      ) async throws

      /// See `WebhooksClient.listLocations`.
      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      /// See `WebhooksClient.getLocation`.
      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      /// See `WebhooksClient.listOperations`.
      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      /// See `WebhooksClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws
    }
  }

  // Default implementations
  extension Clients.WebhooksProtocol {
    public func listWebhooks(request: ListWebhooksRequest) async throws
      -> GoogleCloudDialogflowCXV3.ListWebhooksResponse
    {
      try await self.listWebhooks(request: request, options: .init())
    }

    public func listWebhooks(
      request: ListWebhooksRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.ListWebhooksResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listWebhooksByItems(
      request: ListWebhooksRequest
    ) -> any AsyncSequence<Webhook, Swift.Error> & Sendable {
      self.listWebhooksByItems(request: request, options: .init())
    }

    /// Returns the list of all webhooks in the specified agent.
    ///
    /// @Snippet(path: "Webhooks_ListWebhooks")
    public func listWebhooksByItems(
      request: ListWebhooksRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<Webhook, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws
          -> GoogleCloudDialogflowCXV3.ListWebhooksResponse in
        var request = request
        request.pageToken = token
        return try await self.listWebhooks(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listWebhooksByItems(
      parent: Swift.String,
    ) -> any AsyncSequence<Webhook, Swift.Error> & Sendable {
      let request = ListWebhooksRequest().with {
        $0.parent = parent
      }
      return self.listWebhooksByItems(request: request)
    }

    public func getWebhook(request: GetWebhookRequest) async throws
      -> GoogleCloudDialogflowCXV3.Webhook
    {
      try await self.getWebhook(request: request, options: .init())
    }

    public func getWebhook(
      request: GetWebhookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Webhook {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getWebhook(
      name: Swift.String,
    ) async throws -> GoogleCloudDialogflowCXV3.Webhook {
      let request = GetWebhookRequest().with {
        $0.name = name
      }
      return try await self.getWebhook(request: request)
    }

    public func createWebhook(request: CreateWebhookRequest) async throws
      -> GoogleCloudDialogflowCXV3.Webhook
    {
      try await self.createWebhook(request: request, options: .init())
    }

    public func createWebhook(
      request: CreateWebhookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Webhook {
      throw GoogleGax.RequestError.unimplemented
    }

    public func createWebhook(
      parent: Swift.String,
      webhook: Webhook?,
    ) async throws -> GoogleCloudDialogflowCXV3.Webhook {
      let request = CreateWebhookRequest().with {
        $0.parent = parent
        $0.webhook = webhook
      }
      return try await self.createWebhook(request: request)
    }

    public func updateWebhook(request: UpdateWebhookRequest) async throws
      -> GoogleCloudDialogflowCXV3.Webhook
    {
      try await self.updateWebhook(request: request, options: .init())
    }

    public func updateWebhook(
      request: UpdateWebhookRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowCXV3.Webhook {
      throw GoogleGax.RequestError.unimplemented
    }

    public func updateWebhook(
      webhook: Webhook?,
      updateMask: GoogleWKT.WKTFieldMask?,
    ) async throws -> GoogleCloudDialogflowCXV3.Webhook {
      let request = UpdateWebhookRequest().with {
        $0.webhook = webhook
        $0.updateMask = updateMask
      }
      return try await self.updateWebhook(request: request)
    }

    public func deleteWebhook(request: DeleteWebhookRequest) async throws {
      try await self.deleteWebhook(request: request, options: .init())
    }

    public func deleteWebhook(
      request: DeleteWebhookRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func deleteWebhook(
      name: Swift.String,
    ) async throws {
      let request = DeleteWebhookRequest().with {
        $0.name = name
      }
      try await self.deleteWebhook(request: request)
    }

    public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse
    {
      try await self.listLocations(request: request, options: .init())
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listLocationsByItems(
      request: GoogleCloudLocation.ListLocationsRequest
    ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
      self.listLocationsByItems(request: request, options: .init())
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "Webhooks_ListLocations")
    public func listLocationsByItems(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location
    {
      try await self.getLocation(request: request, options: .init())
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      throw GoogleGax.RequestError.unimplemented
    }

    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      self.listOperationsByItems(request: request, options: .init())
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Webhooks_ListOperations")
    public func listOperationsByItems(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      let listRpc = {
        @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        var request = request
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listOperationsByItems(
      name: Swift.String,
      filter: Swift.String,
    ) -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> & Sendable {
      let request = GoogleLongRunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return self.listOperationsByItems(request: request)
    }

    public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongRunning.Operation {
      let request = GoogleLongRunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      throw GoogleGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }
  }
#else
  @_spi(GoogleCloudInternal) public import GoogleGax

  @available(
    *, unavailable, message: "Enable the 'Webhooks' trait in Package.swift to use this client."
  )
  public final class WebhooksClient: Sendable {
    @available(
      *, unavailable, message: "Enable the 'Webhooks' trait in Package.swift to use this client."
    )
    public init(_ options: GoogleGax.ClientOptions = .init()) throws {}
  }
#endif
